<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
//Labels for methods in the TrackerReporter.php file that are shown in TrackerDashlet
'ShowActiveUsers'      => 'Show Active Users',
'ShowLastModifiedRecords' => 'Last 10 Modified Records',
'ShowTopUser' => 'Top User',
'ShowMyModuleUsage' => 'My Module Usage',
'ShowMyWeeklyActivities' => 'My Weekly Activity',
'ShowTop3ModulesUsed' => 'My Top 3 Modules Used',
'ShowLoggedInUserCount' => 'Active User Count',
'ShowMyCumulativeLoggedInTime' => 'My Cumulative Login Time (This Week)',
'ShowUsersCumulativeLoggedInTime' => 'Users Cumulative Login Time (This Week)',

//Column header mapping
'action' => 'Action',
'active_users' => 'Active User Count',
'date_modified' => 'Date of Last Action',
'different_modules_accessed' => 'Number Of Modules Accessed',
'first_name' => 'First Name',
'item_id' => 'ID',
'item_summary' => 'Name',
'last_action' => 'Last Action Date/Time',
'last_name' => 'Last Name',
'module_name' => 'Module Name',
'records_modified' => 'Total Records Modified',
'top_module' => 'Top Module Accessed',
'total_count' => 'Total Page Views',
'total_login_time' => 'Time (hh:mm:ss)',
'user_name' => 'Username',
'users' => 'Users',

//Administration related labels
'LBL_ENABLE' => 'Включить',
'LBL_MODULE_NAME_TITLE' => 'Trackers',
'LBL_MODULE_NAME' => 'Trackers',
'LBL_TRACKER_SETTINGS' => 'Параметры трекера',
'LBL_TRACKER_QUERIES_DESC' => 'Tracker Queries',
'LBL_TRACKER_QUERIES_HELP' => 'Track SQL statements when "Log slow queries" is enabled and the query execution time exceeds the "Slow query time threshold" value',
'LBL_TRACKER_PERF_DESC' => 'Tracker Performance',
'LBL_TRACKER_PERF_HELP' => 'Track database roundtrips, files accessed and memory usage',
'LBL_TRACKER_SESSIONS_DESC' => 'Tracker Sessions',
'LBL_TRACKER_SESSIONS_HELP' => 'Track active users and users&rsquo; session information',
'LBL_TRACKER_DESC' => 'Трекер',
'LBL_TRACKER_HELP' => 'Отслеживание просмотра (доступ к модулям и записям) и сохранения записей',
'LBL_TRACKER_PRUNE_INTERVAL' => 'Количество дней, в течение которых сохраняются данные трекера',
'LBL_TRACKER_PRUNE_RANGE' => 'Number of days',
);
?>
