<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA ->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the SuiteCRM application.
  *********************************************************************************/
 // Replaced by RAPIRA <-strings = [

$mod_strings = [

    // Module naming
    'LBL_LIST_FORM_TITLE' => 'Миграции',
    'LBL_MODULE_NAME' => 'Миграции',
    'LBL_MODULE_TITLE' => 'Миграции',
    'LBL_HOMEPAGE_TITLE' => 'Мои миграции',
    'LNK_NEW_RECORD' => 'Создать миграцию',
    'LNK_LIST' => 'Миграции',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск миграций',
    'LBL_NEW_FORM_TITLE' => 'Создать миграцию',

    // Module-specific trigger action
    'LBL_RUN_MIGRATION' => 'Запустить процесс миграции',
    'LBL_RUN_MIGRATION_CONFIRMATION' => 'Вы действительно хотите запустить процесс миграции?',

    // Rerun/dismiss confirmation messages (reference this module by name)
	'LBL_RERUN_CONFIRMATION' => 'Вы действительно хотите повторно запустить эту миграцию с нуля? Все существующие элементы, прошедшие миграцию, будут удалены, и миграция будет перезапущена.',
	'LBL_RERUN_SUCCESS' => 'Миграция повторно поставлена ​​в очередь и будет перезапущена сначала.',
	'LBL_DISMISS_CONFIRMATION' => 'Вы действительно хотите закрыть это задание миграции? Будет удалено как само задание, так и все связанные с ней данные.',
	'LBL_DISMISS_SUCCESS' => 'Задание миграции успешно закрыто.',

    // Type footnotes
	'LBL_TYPE_BACKGROUND_HELP' => 'Миграция выполняется в фоновом режиме через обработчик очереди сообщений. Элементы обрабатываются партиями, пользовательский интерфейс в процессе выполнения миграции не блокируется.',
	'LBL_TYPE_IMMEDIATE_HELP' => 'Миграция выполняется немедленно после запуска. Все элементы обрабатываются единым запросом, процесс может занять значительное количество времени при обработке больших объёмов данных.',

    // Messenger setup widget
	'LBL_MESSENGER_SETUP' => 'Настройка фоновых заданий',
	'LBL_MESSENGER_SETUP_DESC1' => 'Задания миграции обрабатываются в фоновом режиме.',
	'LBL_MESSENGER_SETUP_DESC2' => 'Для успешного завершения заданий убедитесь, что запущен обработчик Symfony Messenger.',
	'LBL_MESSENGER_SETUP_DESC3' => 'Без активного обработчика задания останутся в состоянии «Ожидание».',
	'LBL_MESSENGER_SETUP_DOC_LINK' => 'Руководство по настройке (Supervisor, systemd, Cron)',
];
