<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_ID' => 'Изменено(ID)',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_CREATED_ID' => 'Создано(ID)',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
 'LBL_NAME' => 'Название',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Выходные дни',
  'LBL_MODULE_NAME' => 'Выходные дни',
  'LBL_MODULE_TITLE' => 'Выходные дни',
  'LBL_HOMEPAGE_TITLE' => 'Мои выходные дни',
  'LNK_NEW_RECORD' => 'Назначить выходные дни',
  'LNK_LIST' => 'Выходные дни',
  'LNK_IMPORT_AM_PROJECTHOLIDAYS' => 'Импорт выходных дней',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск выходных дней',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AM_PROJECTHOLIDAYS_SUBPANEL_TITLE' => 'Выходные дни',
  'LBL_NEW_FORM_TITLE' => 'Назначение выходных дней',
  'LBL_HOLIDAY_START_DATE' => 'Первый выходной день',
  'LBL_HOLIDAY_END_DATE' => 'Последний выходной день',
  'LBL_FLEX_RELATE' => 'Участники',
  'LBL_HOLIDAY_DATE' => 'Выходные дни',
  'LBL_RESOURSE_USERS' => 'Тип участников',
  'LBL_RESOURCE_ID' => 'Участник (ID)',
  'LBL_RESOURCE_TYPE' => 'Тип участников',
  'LBL_USER' => 'Пользователь',
  'LBL_CONTACT' => 'Контакт'

);