<?php
/*********************************************************************************
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 
 ********************************************************************************/
  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite  ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/

$mod_strings = array(
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ADD_OPTION'     => 'Добавить параметр',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_SECURITYGROUPS' => 'Группы пользователей',
  'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => 'Группы пользователей',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Modified By Id', ///
  'LBL_MODIFIED_NAME' => 'Изменено',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Created By Id', ///
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Название',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_NAME' => 'Название',
  'LBL_EDIT_BUTTON' => 'Править',
  'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Опросы',
  'LBL_MODULE_NAME' => 'Опросы',
  'LBL_MODULE_TITLE' => 'Опросы',
  'LBL_HOMEPAGE_TITLE' => 'Мои опросы',
  'LNK_NEW_RECORD' => 'Создать опрос',
  'LNK_LIST' => 'Опросы',
  'LNK_IMPORT_SURVEYS' => 'Импорт опросов',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск опросов',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_SURVEYS_SUBPANEL_TITLE' => 'Опросы',
  'LBL_NEW_FORM_TITLE' => 'Создать опрос',
  'LBL_STATUS' => 'Статус',
  'LBL_SURVEY_QUESTIONS_DISPLAY' => 'Вопросы',
  'LBL_SURVEY_URL_DISPLAY' => 'Ссылка на опрос',
  'LBL_HAPPINESS_QUESTION' => 'Оценка степени удовлетворённости',
  'LBL_CANT_EDIT_RESPONDED' => 'Вопросы уже не могут быть изменены, если получен хотя бы один ответ.',
  'LBL_VIEW_SURVEY_REPORTS' => 'Просмотр отчётов по опросу',
  'LBL_CHECKED' => 'Отмечено',
  'LBL_UNCHECKED' => 'Не отмечено',
  'LBL_RESPONSE_ANSWER' => 'Ответ',
  'LBL_RESPONSE_CONTACT' => 'Контакт',
  'LBL_RESPONSE_TIME' => 'Дата',
  'LBL_UNKNOWN_CONTACT' => 'Не известен',
  'LBL_RESPONSE_COUNT' => 'Количество',
  'LBL_SUBMIT_TEXT' => 'Текст на кнопке <Отправить>',
  'LBL_SATISFIED_TEXT' => 'Положительный ответ',
  'LBL_NEITHER_TEXT' => 'Нейтральный ответ',
  'LBL_DISSATISFIED_TEXT' => 'Отрицательный ответ',
  'LBL_SURVEYS_SURVEYQUESTIONS_FROM_SURVEYQUESTIONS_TITLE' => 'Вопросы',
  'LBL_SURVEYS_SURVEYRESPONSES_FROM_SURVEYRESPONSES_TITLE' => 'Результаты опроса',
  'LBL_SHOW_RESPONSES' => 'Показать результаты',
  'LBL_HIDE_RESPONSES' => 'Скрыть результаты',
  'LBL_SURVEY_QUESTION' => 'Вопрос',
  'LBL_SURVEY_TEXT' => 'Текст',
  'LBL_SURVEY_TYPE' => 'Тип',
  'LBL_SURVEY_ACTIONS' => 'Управление',
  'LBL_SURVEY_NEW_QUESTION' => 'Новый вопрос',
  'LBL_SURVEY_RESPONSES' => 'Ответов получено',
  'LBL_SURVEYS_SENT' => 'Опросов отправлено:',
  'LBL_SURVEY_DISTINCT' => 'Уникальных опросов отправлено:',
  'LBL_DRAFT' => 'Черновик',
  'LBL_SUBMIT' => 'Отправить',
  'LBL_STARS' => 'Звёзды',
  'LBL_SURVEY_CLOSE_RESPONSE' => 'Благодарим за проявленный интерес, но опрос уже окончен.',
);
