<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания:',
  'LBL_DATE_MODIFIED' => 'Дата изменения:',
  'LBL_MODIFIED' => 'Изменено:',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
  'LBL_CREATED' => 'Создано:',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалён',
  'LBL_NAME' => 'Место проведения события',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_NAME' => 'Место',
  'LBL_EDIT_BUTTON' => 'Править',
  'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Места',
  'LBL_MODULE_NAME' => 'Места',
  'LBL_MODULE_TITLE' => 'Места',
  'LBL_HOMEPAGE_TITLE' => 'Мои места проведения событий',
  'LNK_NEW_RECORD' => 'Назначить место',
  'LNK_LIST' => 'Места',
  'LNK_IMPORT_FP_EVENT_LOCATIONS' => 'Импорт мест',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск мест',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_FP_EVENT_LOCATIONS_SUBPANEL_TITLE' => 'Места',
  'LBL_NEW_FORM_TITLE' => 'Добавить место проведения события',
  'LBL_ADDRESS' => 'Адрес',
  'LBL_ADDRESS_CITY' => 'Город',
  'LBL_ADDRESS_COUNTRY' => 'Страна',
  'LBL_ADDRESS_POSTALCODE' => 'Индекс',
  'LBL_ADDRESS_STATE'  => 'Область',
  'LBL_CAPACITY' => 'Вместимость',
  'LBL_EDITVIEW_PANEL1' => 'Адресные данные',	
  'LBL_FP_EVENT_LOCATIONS_FP_EVENTS_1_FROM_FP_EVENTS_TITLE' => 'События',
);

?>