<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_MODULE_NAME' => 'Контрагенты' ,
'LBL_MODULE_TITLE' => 'Контрагенты - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск контрагентов' ,
'LBL_LIST_FORM_TITLE' => 'Список контрагентов' ,
'LBL_NEW_FORM_TITLE' => 'Создать контрагента' ,
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'LNK_NEW_NOTE' => 'Создать заметку или вложение' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_EMAIL' => 'Отправить E-mail в архив' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'ERR_DELETE_RECORD' => 'Перед удалением контрагента должен быть определён номер записи.' ,
);


?>
