<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$dashletStrings['CalendarDashlet'] = array(
					'LBL_TITLE'            => 'Мой календарь',
                         'LBL_DESCRIPTION'      => 'Календарь',
                         'LBL_CONFIGURE_TITLE'  => 'Заголовок',
                         'LBL_CONFIGURE_VIEW'  => 'Отображать',
                         'LBL_SAVE_BUTTON_LABEL' => 'Сохранить',
                         
                         'LBL_VIEW_DAY' => 'День',
                         'LBL_VIEW_WEEK' => 'Неделю',
                         'LBL_VIEW_MONTH' => 'Месяц',

);
?>
