<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
//module
'LBL_MODULE_NAME' => 'Версии документа' ,

'LNK_NEW_DOCUMENT' => 'Создать документ' ,
'LNK_DOCUMENT_LIST'=> 'Документы' ,

//vardef labels
'LBL_REVISION_NAME' => 'Номер версии' ,
'LBL_FILENAME' => 'Файл:' ,
'LBL_MIME' => 'Тип MIME' ,
'LBL_REVISION' => 'Версия' ,
'LBL_DOCUMENT' => 'Связанные документы' ,
'LBL_LATEST_REVISION' => 'Последняя версия' ,
'LBL_CHANGE_LOG'=> 'Журнал изменений:'  ,
'LBL_ACTIVE_DATE'=> 'Дата публикации' ,
'LBL_EXPIRATION_DATE' => 'Дата окончания' ,
'LBL_FILE_EXTENSION'  => 'Расширение файла' ,
'LBL_DET_CREATED_BY' => 'Кем создано:' ,
'LBL_DET_DATE_CREATED' => 'Дата создания:' ,

'LBL_DOC_NAME' => 'Название документа:' ,
'LBL_DOC_VERSION' => 'Версия:' ,

//document revisions.
'LBL_REV_LIST_REVISION' => 'Версия' ,
'LBL_REV_LIST_ENTERED' => 'Дата создания' ,
'LBL_REV_LIST_CREATED' => 'Создано' ,
'LBL_REV_LIST_LOG'=> 'Журнал изменений:' ,
'LBL_REV_LIST_FILENAME' => 'Файл' ,

'LBL_CURRENT_DOC_VERSION'=> 'Последняя версия:' ,
'LBL_SEARCH_FORM_TITLE'=> 'Поиск документа' ,
'LBL_REVISIONS' => 'Версии',

//error messages
'ERR_FILENAME'=> 'Имя файла' ,
'ERR_DOC_VERSION'=> 'Версия документа' ,
'ERR_DELETE_CONFIRM'=> 'Вы хотите удалить эту версию документа?' ,
'ERR_DELETE_LATEST_VERSION'=> 'Вы не имеете права удалять последнюю версию документа.'  ,
'LNK_NEW_MAIL_MERGE' => 'Слияние',
'LBL_DOC_ID' => 'Источник документа(ID)',
'LBL_DOC_TYPE' => 'Источник',
'LBL_DOC_URL' => 'Источник документа (URL)',
);


?>
