<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ID' => 'ID',
'LBL_DATE_ENTERED' => 'Дата создания',
'LBL_DATE_MODIFIED' => 'Дата изменения',
'LBL_MODIFIED' => 'Изменено',
'LBL_MODIFIED_NAME' => 'Изменено',
'LBL_CREATED' => 'Создано',
'LBL_DESCRIPTION' => 'Описание',
'LBL_DELETED' => 'Удалено',
'LBL_NAME' => 'Название',
'LBL_SAVING' => 'Сохранение...',
'LBL_SAVED' => 'Сохранено',
'LBL_CREATED_USER' => 'Создано',
'LBL_MODIFIED_USER' => 'Изменено',
'LBL_LIST_FORM_TITLE' => 'Лента событий',
'LBL_MODULE_NAME' => 'Лента событий',
'LBL_MODULE_TITLE' => 'Лента событий',
'LBL_DASHLET_DISABLED' => 'Внимание: Лента событий отключена, новые события не будут отображаться в системе',
'LBL_RECORDS_DELETED' => 'Все данные ленты событий были удалены, если лента событий включена, новые события будут отображаться в системе автоматически.',
'LBL_CONFIRM_DELETE_RECORDS' => 'Вы действительно хотите удалить все данные из ленты событий?',
'LBL_FLUSH_RECORDS' => 'Очистить ленту событий',
'LBL_ENABLE_FEED' => 'Включить ленту событий',
'LBL_ENABLE_MODULE_LIST' => 'Включить для следующих модулей',
'LBL_HOMEPAGE_TITLE' => 'Лента событий',
'LNK_NEW_RECORD' => 'Создать событие',
'LNK_LIST' => 'Лента событий',
'LBL_SEARCH_FORM_TITLE' => 'Поиск события',
'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
'LBL_NEW_FORM_TITLE' => 'Создать событие',
'LBL_ALL' => 'Все',
'LBL_USER_FEED' => 'Пользовательские ссылки',
'LBL_ENABLE_USER_FEED' => 'Включить пользовательские ссылки',
'LBL_TO' => 'Visible to Team', ///
'LBL_IS' => ':',
'LBL_DONE' => 'Готово',
'LBL_TITLE' => 'Заголовок:',
'LBL_ROWS' => 'Количество строк:',
'LBL_CATEGORIES' => 'Контролируемые модули:',
'LBL_TIME_LAST_WEEK' => 'на прошлой неделе',
'LBL_TIME_WEEKS' => 'нед.',
'LBL_TIME_DAYS' => 'дн.',
'LBL_TIME_YESTERDAY' => 'вчера',
'LBL_TIME_HOURS' => 'час.',
'LBL_TIME_HOUR' => 'час',
'LBL_TIME_MINUTES' => 'мин.',
'LBL_TIME_MINUTE' => 'минуту',
'LBL_TIME_SECONDS' => 'сек.',
'LBL_TIME_SECOND' => 'секунду',
'LBL_TIME_AND' => 'и',
'LBL_TIME_AGO' => 'назад',

'CREATED_CONTACT' => 'создал(а) <b>НОВЫЙ</b> контакт',
'CREATED_OPPORTUNITY' => 'создал(а) <b>НОВУЮ</b> сделку',
'CREATED_CASE' => 'создал(а) <b>НОВОЕ</b> обращение',
'CREATED_LEAD' => 'создал(а) <b>НОВЫЙ</b> предв. контакт',
'FOR_AMOUNT' => 'на сумму',
'FOR' => 'для',
'CLOSED_CASE' => '<b>ЗАКРЫЛ(а)</b> обращение ',
'CONVERTED_LEAD' => '<b>ПРЕОБРАЗОВАЛ(а)</b> предв. контакт',
'WON_OPPORTUNITY' => ' <b>ЗАКРЫЛ(а) С УСПЕХОМ</b> сделку',
'WITH' => 'с',

'LBL_LINK_TYPE_Link' => 'Ссылка',
'LBL_LINK_TYPE_Image' => 'Изображение',
'LBL_LINK_TYPE_YouTube' => 'YouTube&#153;',

'LBL_SELECT' => 'Выбрать',
'LBL_POST' => 'Опубликовать',
'LBL_AUTHENTICATE' => 'Connect to', ///
'LBL_AUTHENTICATION_PENDING' => 'Not all of the external accounts you have selected have been authenticated. Click \'Cancel\' to return to the Options window to authenticate the external accounts, or click \'Ok\' to proceed without authenticating.', ///
'LBL_ADVANCED_SEARCH' => 'Расширенный фильтр' /*for 508 compliance fix*/,
'LBL_SHOW_MORE_OPTIONS' => 'Доп. параметры',
'LBL_HIDE_OPTIONS' => 'Скрыть параметры',
'LBL_VIEW' => 'View', ///
'LBL_POST_TITLE' => 'Добавление сообщения пользователем ',
'LBL_URL_LINK_TITLE' => 'Адрес ресурса или ссылка на изображение',
);
