<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings['LBL_UPDATE_TEXT'] = 'Текст обновления';
$mod_strings['LBL_INTERNAL'] = 'Внутреннее обновление';
$mod_strings['LBL_AOP_CASE_UPDATES'] = 'Обновления обращения';
$mod_strings['LBL_AOP_CASE_UPDATES_THREADED'] = 'Обновления обращения опубликованы';
$mod_strings['LBL_CASE_UPDATES_COLLAPSE_ALL'] = 'Свернуть все';
$mod_strings['LBL_CASE_UPDATES_EXPAND_ALL'] = 'Развернуть все';
$mod_strings['LBL_NO_CASE_UPDATES'] = "Для данного обращения нет обновлений";
$mod_strings['LBL_AOP_CASE_ATTACHMENTS'] = 'Вложения: ';
