<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings['LBL_AOP_CASE_EVENTS'] = 'События обращения';
$mod_strings['LBL_CASE_ATTACHMENTS_DISPLAY'] = 'Вложения:';
$mod_strings['LBL_ADD_CASE_FILE'] = 'Добавить файл';
$mod_strings['LBL_REMOVE_CASE_FILE'] = 'Удалить файл';
$mod_strings['LBL_SELECT_CASE_DOCUMENT'] = 'Выбрать документ';
$mod_strings['LBL_CLEAR_CASE_DOCUMENT'] = 'Удалить документ';
$mod_strings['LBL_SELECT_INTERNAL_CASE_DOCUMENT'] = 'Документ SuiteCRM';
$mod_strings['LBL_SELECT_EXTERNAL_CASE_DOCUMENT'] = 'Внешний файл';
$mod_strings['LBL_CONTACT_CREATED_BY_NAME'] = 'Создано';
$mod_strings['LBL_CASE_UPDATE_FORM'] = 'Добавить вложение';
