<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA ->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the SuiteCRM application.
  *********************************************************************************/
 // Replaced by RAPIRA <-
$mod_strings = [
    'LBL_MODULE_NAME' => 'Асинхронные задания',
    'LBL_MODULE_TITLE' => 'Асинхронные задания',
    'LBL_LIST_FORM_TITLE' => 'Асинхронные задания',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск асинхронных заданий',
    'LBL_ID' => 'ID',
    'LBL_NAME' => 'Название',
    'LBL_DATE_ENTERED' => 'Создано:',
    'LBL_DATE_MODIFIED' => 'Дата изменения:',
    'LBL_ASYNC_TASK_ID' => 'ID асинхронного задания',
    'LBL_ITEM_KEY' => 'Ключ элемента',
    'LBL_ITEM_NAME' => 'Элемент',
    'LBL_ITEM_MODULE' => 'Элементы асинхронных заданий',
    'LBL_STATUS' => 'Статус',
    'LBL_ERROR_MESSAGE' => 'Сообщение об ошибке',
    'LBL_DATA' => 'Данные',
    'LBL_RESULT_DATA' => 'Результирующие данные',
    'LBL_SORT_ORDER' => 'Сортировка',
    'LBL_RETRY_COUNT' => 'Количество повторов',
    'LBL_ATTACHMENTS' => 'Вложения',
];
