<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_ID' => 'ID',
'LBL_DATE_ENTERED' => 'Дата создания',
'LBL_DATE_MODIFIED' => 'Дата изменения',
'LBL_MODIFIED' => 'Изменено',
'LBL_MODIFIED_NAME' => 'Изменено',
'LBL_CREATED' => 'Создано',
'LBL_DESCRIPTION' => 'Описание',
'LBL_DELETED' => 'Удалено',
'LBL_NAME' => 'Название',
'LBL_CREATED_USER' => 'Создано',
'LBL_MODIFIED_USER' => 'Изменено',
'LBL_LIST_NAME' => 'Название',
'LBL_EDIT_BUTTON' => 'Править',
'LBL_REMOVE' => 'Удалить',
'LBL_ASCENDING' => 'Восходящая',
'LBL_DESCENDING' => 'Нисходящая',

// Emails
'LBL_OPT_IN' => 'Подтвердить подписку',
'LBL_OPT_IN_PENDING_EMAIL_NOT_SENT' => 'Ожидание подтверждения подписки, письмо с запросом на подтверждение НЕ отправлено.',
'LBL_OPT_IN_PENDING_EMAIL_SENT' => 'Ожидание подтверждения подписки, отправлено письмо с запросом на подтверждение.',
'LBL_OPT_IN_CONFIRMED' => 'Двойное подтверждение подписки.',
	
);
