<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings['LBL_ASSIGNED_TO_ID'] = 'Ответственный(ая)';
$mod_strings['LBL_ASSIGNED_TO_NAME'] = 'Ответственный(ая)';
$mod_strings['LBL_ID'] = 'ID';
$mod_strings['LBL_DATE_ENTERED'] = 'Создано';
$mod_strings['LBL_DATE_MODIFIED'] = 'Изменено';
$mod_strings['LBL_MODIFIED'] = 'Изменено';
$mod_strings['LBL_MODIFIED_ID'] = 'Изменено(ID)';
$mod_strings['LBL_MODIFIED_NAME'] = 'Изменено (Имя)';
$mod_strings['LBL_CREATED'] = 'Создано';
$mod_strings['LBL_CREATED_ID'] = 'Создано(ID)';
$mod_strings['LBL_DESCRIPTION'] = 'Описание';
$mod_strings['LBL_DELETED'] = 'Удалено';
$mod_strings['LBL_NAME'] = 'Адрес';
$mod_strings['LBL_CREATED_USER'] = 'Создано';
$mod_strings['LBL_MODIFIED_USER'] = 'Изменено';
$mod_strings['LBL_LIST_NAME'] = 'Адрес';
$mod_strings['LBL_LIST_FORM_TITLE'] = 'Кэш адресов';
$mod_strings['LBL_MODULE_NAME'] = 'Кэш адресов';
$mod_strings['LBL_MODULE_TITLE'] = 'Кэш адресов';
$mod_strings['LBL_HOMEPAGE_TITLE'] = 'Мой кэш адресов';
$mod_strings['LNK_NEW_RECORD'] = 'Добавить в кэш адресов';
$mod_strings['LNK_LIST'] = 'Кэш адресов';
$mod_strings['LNK_IMPORT_JJWG_ADRESS_CACHE'] = 'Импорт кэша адресов';
$mod_strings['LBL_SEARCH_FORM_TITLE'] = 'Поиск кэша адресов';
$mod_strings['LBL_HISTORY_SUBPANEL_TITLE'] = 'История';
$mod_strings['LBL_ACTIVITIES_SUBPANEL_TITLE'] = 'Мероприятия';
$mod_strings['LBL_JJWG_ADRESS_CACHE_SUBPANEL_TITLE'] = 'Кэш адресов';
$mod_strings['LBL_NEW_FORM_TITLE'] = 'Новый кэш адресов';
$mod_strings['LBL_LAT'] = 'Широта';
$mod_strings['LBL_LNG'] = 'Долгота';
$mod_strings['LBL_GEOCODE_STATUS'] = 'Геокод';
$mod_strings['LBL_CURRENT_USER_FILTER'] = 'Мои записи';
$mod_strings['LBL_ASSIGNED_TO'] = 'Ответственный(ая) ';
$mod_strings['LNK_IMPORT_JJWG_ADDRESS_CACHE'] = 'Импорт кэша адресов';
$mod_strings['LBL_JJWG_ADDRESS_CACHE_SUBPANEL_TITLE'] = 'Кэш адресов';

?>