<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_ROLE' => 'Роль: ' ,
'LBL_LANGUAGE' => 'Язык: ' ,
'LBL_MODULE_NAME' => 'Роли' ,
'LBL_MODULE_TITLE' => 'Роли - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск роли' ,
'LBL_LIST_FORM_TITLE' => 'Список ролей' ,
'LNK_NEW_ROLE' => 'Создать роль' ,
'LNK_ROLES' => 'Роли' ,
'LBL_NAME' => 'Имя: ' ,
'LBL_DESCRIPTION' => 'Описание: ' ,
'LBL_ALLOWED_MODULES' => 'Разрешённые модули: ' ,
'LBL_DISALLOWED_MODULES' => 'Неразрешённые модули: ' ,
'LBL_ASSIGN_MODULES' => 'Править модули: ' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Роли' ,
'LBL_USERS'=> 'Пользователи' ,

'LBL_USERS_SUBPANEL_TITLE' => 'Пользователи'  ,
);
?>
