<?php
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая):',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая):',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания:' ,
  'LBL_DATE_MODIFIED' => 'Дата изменения:' ,
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Текст статьи',
  'LBL_ADDITIONAL_INFO' => 'Резолюция',
  'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Статья',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_NAME' => 'Имя',
  'LBL_EDIT_BUTTON' => 'Править',
  'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Ствтьи базы знаний',
  'LBL_MODULE_NAME' => 'База знаний',
  'LBL_MODULE_TITLE' => 'База знаний',
  'LBL_HOMEPAGE_TITLE' => 'Моя база знаний',
  'LNK_NEW_RECORD' => 'Добавить статью в базу знаний',
  'LNK_LIST' => 'Статьи базы знаний',
  'LNK_IMPORT_AOK_KNOWLEDGEBASE' => 'Импорт статей базы знаний',
  'LBL_SEARCH_FORM_TITLE' => 'Помск статей базы знаний',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AOK_KNOWLEDGEBASE_SUBPANEL_TITLE' => 'Статьи базы знаний',
  'LBL_NEW_FORM_TITLE' => 'Новая статья базы знаний',
  'LBL_STATUS' => 'Статус',
  'LBL_REVISION' => 'Версия статьи',
  'LBL_AUTHOR_USER_ID' => 'Автор(ID)',
  'LBL_AUTHOR' => 'Автор статьи',
  'LBL_APPROVER_USER_ID' => 'Кем утверждено(ID)',
  'LBL_APPROVER' => 'Кем утверждено',
);

$mod_strings['LBL_AOK_KB_CATEGORIES_TITLE'] = 'Категории базы знаний';