<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}
$dashletStrings['SpotsDashlet'] = array(
    'LBL_TITLE' => 'Сводки',
    'LBL_DESCRIPTION' => 'Сводный отчёт',
    'LBL_SAVING' => 'Сохранение сводок ...',
    'LBL_SAVED' => 'Сохранено',
    'LBL_CONFIGURE_TITLE' => 'Заголовок:',
    'LBL_SPOTS_TO_LOAD' => 'Сводка:',
    'LBL_NO_SPOTS_SELECTED' => 'Не выбрано ни одной сводки',
    'LBL_SPOTS_POINTED_DELETED' => 'Сводка была удалена',
    'LBL_SHOW_UI' => 'Настраиваемая сводка',
    'LBL_NAME' => 'Название',
);
