<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(

'LBL_ADMINISTRATION_MAIN' => 'Параметры подключения',
'LBL_AVAILABLE' => 'Доступно',
'LBL_BACK' => '< Назад',
'LBL_CONFIRM_CONTINUE_SAVE' => 'Некоторые поля, требующие обязательного заполнения, оставлены пустыми. Продолжить сохранение?',
'LBL_CONNECTOR_FIELDS' => 'Поля подключения',
'LBL_DATA' => 'Данные',
'LBL_DEFAULT' => 'По умолчанию',
'LBL_DISABLED' => 'Отключённые модули',
'LBL_ENABLED' => 'Подключённые модули',
'LBL_EXTERNAL' => 'Разрешать пользователям создавать внешние учётные записи для данного подключения. Соответствующие параметры должны быть так же указаны на странице настроек параметров подключения.',
'LBL_EXTERNAL_SET_PROPERTIES' => ' Соответствующие параметры должны быть также указаны на странице настроек параметров подключения.',
'LBL_MERGE' => 'Объединить',
'LBL_MODIFY_DISPLAY_TITLE' => 'Выбор модулей',
'LBL_MODIFY_DISPLAY_DESC' => 'Выбор модулей, связанных с указанным подключением.',
'LBL_MODULE_FIELDS' => 'Поля модуля',
'LBL_MODIFY_MAPPING_TITLE' => 'Настройка полей',
'LBL_MODIFY_MAPPING_DESC' => 'Настройка соответствия полей подключения полям модулей. Данные полей подключения будут объединены с данными полей модулей.',
'LBL_MODIFY_PROPERTIES_TITLE' => 'Настройка URL подключения',
'LBL_MODIFY_PROPERTIES_DESC' => 'Настройка параметров подключения.',
'LBL_MODIFY_SEARCH_TITLE' => 'Управление поиском данных в подключении',
'LBL_MODIFY_SEARCH' => 'Поиск',
'LBL_MODIFY_SEARCH_DESC' => 'Выбор полей подключения для поиска необходимых данных.',
'LBL_MODULE_NAME' => 'Подключения',
'LBL_NO_PROPERTIES' => 'Для данного подключения нет настраиваемых параметров.',
'LBL_SAVE' => 'Сохранить',
'LBL_SUMMARY' => 'Резюме',
'LBL_STEP1' => 'Поиск и просмотр данных',
'LBL_STEP2' => 'Объединение записей с',
'LBL_TEST_SOURCE' => 'Тестирование подключения',
'LBL_TEST_SOURCE_FAILED' => 'Тест не пройден',
'LBL_TEST_SOURCE_SUCCESS' => 'Тест успешно пройден',
'LBL_TITLE' => 'Объединение данных',

'ERROR_NO_ADDITIONAL_DETAIL' => 'Ошибка: Для данной записи не обнаружено дополнительной информации.',
'ERROR_NO_SEARCHDEFS_DEFINED' => 'Для данного подключения не указан ни один модуль. Укажите модуль на странице выбора модулей.',
'ERROR_NO_SEARCHDEFS_MAPPED' => 'Ошибка: Нет подключений с настроенными для поиска полями.',
'ERROR_NO_SEARCHDEFS_MAPPING' => 'Ошибка: Не определены поля поиска для модуля и подключения. Для решения проблемы свяжитесь с системным администратором.',
'ERROR_NO_DISPLAYABLE_MAPPED_FIELDS' => 'Ошибка: Не указано ни одного поля модуля для отображения в результирующих данных. Обратитесь к системному администратору.',
'LBL_INFO_INLINE' => 'Info' /*for 508 compliance fix*/,
'LBL_CLOSE' => 'Закрыть' /*for 508 compliance fix*/,
);
