<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_ID' => 'Изменено(ID)',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_CREATED_ID' => 'Создано(ID)',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
 'LBL_NAME' => 'Название',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Шаблоны проектных задач',
  'LBL_MODULE_NAME' => 'Шаблоны проектных задач',
  'LBL_MODULE_TITLE' => 'Шаблоны проектных задач',
  'LBL_HOMEPAGE_TITLE' => 'Мои шаблоны проектных задач',
  'LNK_NEW_RECORD' => 'Создать шаблон проектной задачи',
  'LNK_LIST' => 'Шаблоны проектных задач',
  'LNK_IMPORT_AM_TASKTEMPLATES' => 'Импорт шаблонов проектных задач',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск шаблонов проектных задач',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AM_TASKTEMPLATES_SUBPANEL_TITLE' => 'Шаблоны проектных задач',
  'LBL_NEW_FORM_TITLE' => 'Создание шаблона проектной задачи',
  'LBL_STATUS' => 'Статус',
  'LBL_PRIORITY' => 'Приоритет',
  'LBL_PERCENT_COMPLETE' => 'Процент выполнения',
  'LBL_PREDECESSORS' => 'Предшественники',
  'LBL_MILESTONE_FLAG' => 'Контрольная точка',
  'LBL_RELATIONSHIP_TYPE' => 'Тип связи',
  'LBL_TASK_NUMBER' => 'Номер задачи',
  'LBL_ORDER_NUMBER' => 'Порядковый номер в проекте',
  'LBL_ESTIMATED_EFFORT' => 'Оценка усилий (час.)',
  'LBL_UTILIZATION' => 'Расход ресурсов (%)',
  'LBL_DURATION' => 'Продолжительность (дни)',
  'LBL_AM_TASKTEMPLATES_AM_PROJECTTEMPLATES_FROM_AM_PROJECTTEMPLATES_TITLE' => 'Шаблон проекта',
);