<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
  'LBL_ID' => 'ID',
  'LBL_MODULE_NAME' => 'Группы',
  'LBL_DATE_ENTERED' => 'Создано',
  'LBL_DATE_MODIFIED' => 'Изменено',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалена',
  'LBL_NAME' => 'Группа',
  'LBL_TOTAL_AMT' => 'Итого без скидки',
  'LBL_DISCOUNT_AMOUNT' => 'Скидка',
  'LBL_SUBTOTAL_AMOUNT' => 'Итого со скидкой',
  'LBL_TAX_AMOUNT' => 'Всего НДС',
  'LBL_SUBTOTAL_TAX_AMOUNT' => 'Итого учётом скидки и НДС',
  'LBL_GROUP_TOTAL' => 'ИТОГО С НДС',
  'LBL_LIST_NUM' => '№',
  
  'LBL_SUBTOTAL_AMOUNT_USDOLLAR' => 'Итого со скидкой (основная валюта)',
  'LBL_DISCOUNT_AMOUNT_USDOLLAR' => 'Скидка (основная валюта)',
  'LBL_TAX_AMOUNT_USDOLLAR' => 'Всего НДС (основная валюта)',
  'LBL_TOTAL_AMT_USDOLLAR' => 'Итого без скидки (основная валюта)',
  'LBL_GROUP_TOTAL_USDOLLAR' => 'ИТОГО С НДС (основная валюта)',
  'LBL_SUBTOTAL_TAX_AMOUNT_USDOLLAR' => 'Итого учётом скидки и НДС (основная валюта)',
);
?>
