<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_MODULE_NAME' => 'Ошибки',
'LBL_MODULE_TITLE' => 'Ошибки - главная',
'LBL_MODULE_ID' => 'Ошибки',
'LBL_SEARCH_FORM_TITLE' => 'Поиск ошибок',
'LBL_LIST_FORM_TITLE' => 'Ошибки',
'LBL_NEW_FORM_TITLE' => 'Описать ошибку',
'LBL_SUBJECT' => 'Ошибка:',
'LBL_NUMBER' => 'Номер:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_PRIORITY' => 'Приоритет:' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_CONTACT_NAME' => 'Контактное лицо:' ,
'LBL_CONTACT_ROLE' => 'Роль:' ,
'LBL_LIST_NUMBER' => 'Ном.' ,
'LBL_LIST_SUBJECT' => 'Ошибка' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LIST_PRIORITY' => 'Приоритет' ,
'LBL_LIST_RESOLUTION' => 'Резолюция' ,
'LBL_LIST_LAST_MODIFIED' => 'Последнее изменение' ,
'LBL_INVITEE' => 'Контакты' ,
'LBL_TYPE' => 'Тип:' ,
'LBL_LIST_TYPE' => 'Тип' ,
'LBL_RESOLUTION' => 'Резолюция:' ,
'LBL_RELEASE' => 'Версия:' ,
'LNK_NEW_BUG' => 'Новая ошибка',
'LNK_BUG_LIST' => 'Ошибки',
'ERR_DELETE_RECORD' => 'Вы должны указать номер записи для удаления ошибки.' ,
'LBL_LIST_MY_BUGS' => 'Мои ошибки' ,
'LNK_IMPORT_BUGS' => 'Импорт ошибок',
'LBL_FOUND_IN_RELEASE' => 'Обнаружено в версии:' ,
'LBL_FIXED_IN_RELEASE' => 'Исправлено в версии:' ,
'LBL_LIST_FIXED_IN_RELEASE' => 'Исправлено в версии:',
'LBL_WORK_LOG' => 'Журнал:' ,
'LBL_SOURCE' => 'Источник:' ,
'LBL_PRODUCT_CATEGORY' => 'Категория:' ,

'LBL_CREATED_BY' => 'Кем создано:' ,
'LBL_MODIFIED_BY' => 'Последнее изменение:' ,

'LBL_LIST_EMAIL_ADDRESS' => 'Адрес E-mail' ,
'LBL_LIST_CONTACT_NAME' => 'Контактное лицо' ,
'LBL_LIST_ACCOUNT_NAME' => 'Контрагент' ,
'LBL_LIST_PHONE' => 'Тел.' ,
'NTC_DELETE_CONFIRMATION' => 'Вы действительно хотите удалить этот контакт из данной ошибки?' ,

'LBL_DEFAULT_SUBPANEL_TITLE' => 'Ошибки' ,
'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия' ,
'LBL_HISTORY_SUBPANEL_TITLE' => 'История' ,
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'Контрагенты' ,
'LBL_CASES_SUBPANEL_TITLE' => 'Обращения' ,
'LBL_PROJECTS_SUBPANEL_TITLE' => 'Проекты',
'LBL_DOCUMENTS_SUBPANEL_TITLE' => 'Документы',
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',

'LBL_BUG_INFORMATION' => 'Основная информация',

//For export labels


);
