<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

// Replaced by RAPIRA ->
********************************************************************************/
/*********************************************************************************
 *
* This file was generated by the RAPIRA Translation Suite ----------
*
***********************************************************************likhobory*/

/*********************************************************************************
 * Description: Defines the Russian language pack for the SuiteCRM application.
*********************************************************************************/
// Replaced by RAPIRA <-

$mod_strings = [
    // System fields
    'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
    'LBL_ASSIGNED_TO_NAME' => 'Пользователь: ',
    'LBL_DATE_ENTERED' => 'Дата ввода:' ,
    'LBL_DATE_MODIFIED' => 'Дата изменения:' ,
    'LBL_MODIFIED' => 'Изменено' ,
    'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
    'LBL_CREATED' => 'Создано' ,
    'LBL_CREATED_USER' => 'Создано',
    'LBL_MODIFIED_USER' => 'Изменено',
    'LBL_DESCRIPTION' => 'Описание',
    'LBL_DELETED' => 'Удалено',

    // Security groups
    'LBL_SECURITYGROUPS' => 'Группы пользователей',
    'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => 'Группы пользователей',

    // List view labels
    'LBL_LIST_NAME' => 'Название',
    'LBL_LIST_DELETE' => 'Удалить',
    'LBL_EDIT_BUTTON' => 'Править',
    'LBL_REMOVE' => 'Удалить',
    'LBL_ASCENDING' => 'Восходящая',
    'LBL_DESCENDING' => 'Нисходящая',

    // Email opt-in labels
    'LBL_OPT_IN' => 'Подписан',
    'LBL_OPT_IN_PENDING_EMAIL_NOT_SENT' => 'Ожидание подтверждения подписки, письмо с запросом на подтверждение НЕ отправлено.',
    'LBL_OPT_IN_PENDING_EMAIL_SENT' => 'Ожидание подтверждения подписки, отправлено письмо с запросом на подтверждение.',
    'LBL_OPT_IN_CONFIRMED' => 'Подписан',

    // Subpanel titles
    'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
    'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
    'LBL_CALENDARACCOUNT_SUBPANEL_TITLE' => 'Учётные записи календаря',
    'LBL_MEETINGS_SUBPANEL_TITLE' => 'Синхронизированные встречи',

    // Import links
    'LNK_IMPORT_CALENDARACCOUNT' => 'Импорт учётных записей календаря',

    // Additional menu links
    'LNK_LIST_CREATE_NEW_GROUP' => 'Создать групповую учётную запись календаря',
    'LNK_LIST_CREATE_NEW_PERSONAL' => 'Создать персональную учётную запись календаря',
    'LNK_LIST_INBOUND_EMAILS' => 'Учётные записи входящей почты',
    'LNK_LIST_OUTBOUND_EMAILS' => 'Учётные записи исходящей почты',
    'LNK_LIST_EXTERNAL_OAUTH_PROVIDERS' => 'Внешние провайдеры OAuth',
    'LNK_LIST_EXTERNAL_OAUTH_CONNECTIONS' => 'Внешние подключения OAuth',

    // Basic module labels
    'LBL_MODULE_NAME' => 'Учётные записи календаря',
    'LBL_MODULE_TITLE' => 'Учётные записи календаря',
    'LBL_LIST_FORM_TITLE' => 'Учётные записи календаря',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск учётных записей календаря',
    'LBL_NEW_FORM_TITLE' => 'Создать учётную запись календаря',
    'LBL_HOMEPAGE_TITLE' => 'Мои учётные записи календаря',

    // Navigation links
    'LNK_NEW_RECORD' => 'Создать учётную запись календаря',
    'LNK_LIST' => 'Учётные записи календаря',

    // Standard fields
    'LBL_NAME' => 'Название',
    'LBL_ID' => 'ID',
    'LBL_TYPE' => 'Тип',
    'LBL_SOURCE' => 'Источник',

    // OAuth2 Fields
    'LBL_OAUTH_CONNECTION' => 'Подключение OAuth',
    'LBL_CONNECT_OAUTH' => 'Connect OAuth',

    // Basic Auth Fields
    'LBL_USERNAME' => 'Логин',
    'LBL_PASSWORD' => 'Пароль',
    'LBL_SERVER_URL' => 'URL сервера',
    'LBL_TEST_CONNECTION' => 'Проверить подключение',

    // API Key Fields
    'LBL_API_KEY' => 'Ключ API Key',
    'LBL_API_ENDPOINT' => 'Конечная точка api',
    'LBL_VALIDATE_API' => 'Проверить API',

    // Calendar User Fields
    'LBL_CALENDAR_USER_ID' => 'ID пользователя календаря',
    'LBL_CALENDAR_USER_NAME' => 'Пользователь календаря',
    'LBL_CALENDAR_USER' => 'Пользователь календаря',

    // Auth Actions
    'LBL_AUTH_ACTIONS' => 'Аутентификация',

    // Panel Labels
    'LBL_SYNC_STATUS' => 'Статус синхронизации',

    // Connection Status Fields
    'LBL_LAST_CONNECTION_STATUS' => 'Тест успешно пройден',
    'LBL_LAST_CONNECTION_TEST' => 'Последняя проверка',
    'LBL_LAST_SYNC_ATTEMPT_DATE' => 'Последняя попытка синхронизации',
    'LBL_LAST_SYNC_ATTEMPT_STATUS' => 'Статус синхронизации',
    'LBL_LAST_SYNC_ATTEMPT_MESSAGE' => 'Сообщение синхронизации',
    'LBL_LAST_SYNC_DATE' => 'Дата последней синхронизации',
    'LBL_EXTERNAL_CALENDAR_ID' => 'ID внешнего календаря',
    'LBL_DUPLICATE_EXTERNAL_CALENDAR' => 'Этот внешний календарь уже подключен к учётной записи',

    // Sync Actions
    'LBL_SYNC_NOW' => 'Синхронизировать',
    'LBL_SYNC_NOW_TITLE' => 'Синхронизировать учётную запись календаря',
    'LBL_SYNC_NOW_CONFIRM' => 'Вы действительно хотите синхронизировать учётную запись календаря?',
    'LBL_NO_ACCOUNT_ID' => 'Не указан ID учётной записи календаря',
    'LBL_SYNCING' => 'Синхронизация...',
    'LBL_NETWORK_ERROR' => 'В процессе синхронизации произошла ошибка. Попробуйте ещё раз.',
    'LBL_UNKNOWN' => 'Unknown', ///
    'LBL_NOW' => 'now', ///
    'LBL_SYNC_SUCCESS' => 'Синхронизация календаря успешно завершена.',
    'LBL_SYNC_FAILED' => 'В процессе синхронизации произошла ошибка.',
    'LBL_SYNC_FAILED_DEFAULT' => 'В процессе синхронизации произошла ошибка. Проверьте файл журнала.',
    'LBL_SYNC_RESPONSE_ERROR' => 'В процессе обработки ответа синхронизации произошла ошибка. Проверьте файл журнала.',
    'LBL_SYNC_IN_PROGRESS' => 'Синхронизация уже начата. Подождите...',
    'LBL_SYNC_IN_PROGRESS_MESSAGE' => 'Синхронизация событий календаря. Это может занять некоторое время...',
    'LBL_PLEASE_WAIT' => 'Подождите',
    // Permission and validation messages
    'LBL_NO_ACCESS' => 'У вас недостаточно прав для выполнения этой операции',
    'LBL_ALREADY_HAS_PERSONAL_ACCOUNT' => 'У этого пользователя уже есть персональная учётная запись календаря.',
    'LBL_ADMIN_ONLY_GROUP_ACCOUNT' => 'Только администраторы могут создавать групповые учётные записи календаря.',

    // Authentication validation messages
    'LBL_OAUTH_CONNECTION_REQUIRED' => 'Сначала выберите подключение OAuth.',
    'LBL_BASIC_AUTH_FIELDS_REQUIRED' => 'Заполните поля, необходимые для аутентификации (логин, пароль, URL сервера).',
    'LBL_API_KEY_REQUIRED' => 'Укажите ключ API.',
    'LBL_USING_SAVED_API_KEY' => 'Использован предыдущий сохранённый ключ API.',
    'LBL_UNKNOWN_AUTH_METHOD' => 'Неизвестный метод аутентификации',
    'LBL_SELECT_CALENDAR_SOURCE_FIRST' => 'Сначала выберите источник календаря.',

    // Connection test messages
    'LBL_CALENDAR' => 'Календарь',
    'LBL_SUCCESSFUL' => 'Проверка успешно завершена',
    'LBL_FAILED' => 'В процессе проверки произошла ошибка',
    'LBL_CONNECTION_TEST' => 'Проверить подключение',
    'LBL_YES' => 'Да',
    'LBL_NO' => 'Нет',
    'LBL_FOUND_CALENDARS' => 'Обнаружено календарей: {count}.',
    'LBL_CONNECTION_TEST_RESPONSE_ERROR' => 'В процессе обработки ответа синхронизации произошла ошибка. Проверьте файл журнала.',
    'LBL_CONNECTION_TEST_HTTP_ERROR' => 'В процессе проверки произошла ошибка, статус HTTP',
    'LBL_CONNECTION_NETWORK_ERROR' => 'В процессе проверки произошла ошибка. Попробуйте ещё раз.',
    'LBL_CONNECTION_TEST_SUCCESS_MESSAGE' => 'Проверка подключения успешно завершена.<br>Параметры подключения верны, календарь доступен.',
    'LBL_DUPLICATE_CALENDAR_ERROR' => 'Календарь уже подключён к учётной записи',

    // Authentication method error messages
    'LBL_AUTH_METHOD_ERROR' => 'Ошибка определения метода аутентификации',
    'LBL_AUTH_METHOD_PARSE_ERROR' => 'Ошибка разбора ответа метода аутентификации',
    'LBL_AUTH_METHOD_GET_ERROR' => 'Ошибка получения метода аутентификации для источника',

    // Dialog labels
    'LBL_NOTIFICATION' => 'Уведомление',
    'LBL_CONFIRM' => 'Подтверждение',
    'LBL_ARE_YOU_SURE' => 'Вы уверены?',

    // Sync status enum translations
    'LBL_SYNC_STATUS_IN_PROGRESS' => 'В процессе',
    'LBL_SYNC_STATUS_SUCCESS' => 'Успешна',
    'LBL_SYNC_STATUS_WARNING' => 'Предупреждение',
    'LBL_SYNC_STATUS_ERROR' => 'Ошибка',

    // Sync message enum translations
    'LBL_SYNC_MSG_SYNC_COMPLETE' => 'Все встречи синхронизированы.',
    'LBL_SYNC_MSG_UP_TO_DATE' => 'Нет новых встреч для синхронизации.',
    'LBL_SYNC_MSG_MEETINGS_FAILED' => 'Некоторые встречи не удалось синхронизировать. Проверьте файл журнала.',
    'LBL_SYNC_MSG_SYNC_PARTIAL' => 'Часть встреч синхронизирована. Оставшаяся часть ожидает в очереди из-за настроенных администратором ограничений синхронизации.',
    'LBL_SYNC_MSG_SYNC_ERROR' => 'Ошибка синхронизации. Проверьте файл журнала.',
    'LBL_SYNC_MSG_TOKEN_EXPIRED' => 'Срок действия токена аутентификации истек.',
    'LBL_SYNC_MSG_CONNECTION_ERROR' => 'Ошибка подключения.',
    'LBL_SYNC_MSG_CALENDAR_NOT_FOUND' => 'Календарь не обнаружен.',

    // Relationship labels
    'LBL_MEETINGS' => 'Встречи',
];