<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (

'LBL_NAME' => 'Имя:' ,
'LBL_NUMBER' => 'Номер:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_PRIORITY' => 'Приоритет:' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_RESOLUTION' => 'Резолюция:' ,
'LBL_LAST_MODIFIED' => 'Последнее изменение',
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
'LBL_ASSIGNED_TO_NAME' => 'Пользователь: ',
'LBL_WORK_LOG' => 'Журнал',
'LBL_CREATED_BY' => 'Кем создано:',
'LBL_DATE_CREATED' => 'Дата создания:',
'LBL_DATE_ENTERED' => 'Дата ввода:' ,
'LBL_DATE_MODIFIED'=> 'Дата изменения:' ,
'LBL_MODIFIED_BY' => 'Кем изменено:',
'LBL_ASSIGNED_USER' => 'Ответственный(ая):',
'LBL_SYSTEM_ID' => 'System ID' ,
'LBL_TYPE'=> 'Тип',
'LBL_SUBJECT' => 'Тема:',

'LBL_EDIT_BUTTON' => 'Править',
'LBL_REMOVE' => 'Удалить',

);
?>
