<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_MODULE_TITLE' => 'Мои сохранённые условия поиска',

'LBL_SEARCH_FORM_TITLE' => 'Мои сохранённые условия поиска : Поиск',
'LBL_LIST_FORM_TITLE' => 'Список условий поиска',
'LBL_DELETE_CONFIRM' => 'Вы действительно хотите удалить выбранное условие поиска?',
'LBL_UPDATE_BUTTON_TITLE' => 'Обновить эти условия поиска',
'LBL_DELETE_BUTTON_TITLE' => 'Удалить эти условия поиска',
'LBL_SAVE_BUTTON_TITLE' => 'Сохранить текущие условия поиска',
'LBL_LIST_NAME' => 'Имя',
'LBL_LIST_MODULE' => 'Модуль',
'LBL_ORDER_BY_COLUMNS' => 'Сортировать по колонке:',
'LBL_DIRECTION' => 'Сортировка:',
'LBL_SAVE_SEARCH_AS' => 'Сохранить условия поиска:',
'LBL_SAVE_SEARCH_AS_HELP' => 'Сохраняет условия поиска, включая фильтры на закладке расширенного поиска.',
'LBL_PREVIOUS_SAVED_SEARCH' => 'Условия поиска:',
'LBL_PREVIOUS_SAVED_SEARCH_HELP' => 'Удаление или редактирование существующих условий поиска.',
'LBL_ASCENDING' => 'Восходящая',
'LBL_DESCENDING' => 'Нисходящая',
'LBL_MODIFY_CURRENT_SEARCH'=> 'Условие поиска',

);


?>
