<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA ->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the SuiteCRM application.
  *********************************************************************************/
 // Replaced by RAPIRA <-
$mod_strings = [

    // Standard record field labels
    'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
    'LBL_ASSIGNED_TO_NAME' => 'Пользователь:',
    'LBL_ID' => 'ID',
    'LBL_DATE_ENTERED' => 'Создано:',
    'LBL_DATE_MODIFIED' => 'Дата изменения:',
    'LBL_MODIFIED' => 'Изменено',
    'LBL_MODIFIED_NAME' => 'Изменено',
    'LBL_CREATED' => 'Создано',
    'LBL_DESCRIPTION' => 'Описание',
    'LBL_DELETED' => 'Удалено',
    'LBL_NAME' => 'Название',
    'LBL_CREATED_USER' => 'Создано',
    'LBL_MODIFIED_USER' => 'Изменено',
    'LBL_LIST_NAME' => 'Название',
    'LBL_EDIT_BUTTON' => 'Править',
    'LBL_REMOVE' => 'Удалить',
    'LBL_LIST_DELETE' => 'Удалить',
    'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
    'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',

    // Async task field labels
    'LBL_DATA' => 'Данные',
    'LBL_TYPE' => 'Тип',
    'LBL_ESTIMATED_RUN_TIME' => 'Предполагаемое время выполнения',
    'LBL_STATUS' => 'Статус',
    'LBL_SERVICE_KEY' => 'Ключ службы',
    'LBL_LAST_RUN_DATETIME' => 'Последний запуск',
    'LBL_ATTACHMENTS' => 'Вложения',
    'LBL_PHASE' => 'Этап',
    'LBL_OWNER' => 'Владелец',

    // Progress field labels
    'LBL_PROGRESS' => 'Выполнение',
    'LBL_PROGRESS_PERCENT' => 'Процент',
    'LBL_PROGRESS_COMPLETED' => 'Завершено',
    'LBL_PROGRESS_FAILED' => 'Ошибка',
    'LBL_PROGRESS_PERCENT_TPL' => '{{fields.progress.attributes.percent|default:-}}% (Успешно:{{fields.progress.attributes.completed|default:-}}, Ошибок: {{fields.progress.attributes.failed|default:-}} / Всего: {{fields.progress.attributes.total|default:-}})',
    'LBL_PROGRESS_NOT_STARTED' => 'Не начато',
    'LBL_PROGRESS_QUEUING_TPL' => 'Элементов в очереди: {{fields.progress.attributes.total|default:0}}',

    // Action labels — button text (shared across modules)
    'LBL_RETRY' => 'Повторить',
    'LBL_RERUN' => 'Перезапустить',
    'LBL_DISMISS' => 'Закрыть',
    'LBL_DELETE' => 'Удалить',
    'LBL_DELETE_COMPLETED_CONFIRMATION' => 'Вы действительно хотите удалить это выполненное задание?',
  	'LBL_DELETE_COMPLETED_WITH_FAILURES_CONFIRMATION' => 'Это задание завершилось с ошибками. Его удаление приведет к удалению всех данных задания, включая сведения об ошибках. Вы действительно хотите продолжить?',
	'LBL_DELETE_FAILED_CONFIRMATION' => 'Это задание не было выполнено. Его удаление приведет к удалению всех данных задания, включая сведения об ошибках. Вы действительно хотите продолжить?',

    // Retry action messages (shared — generic phrasing)
    'LBL_RETRY_CONFIRMATION' => 'Вы действительно хотите повторить? Все необработанные элементы будут повторно поставлены в очередь.',
    'LBL_RETRY_SUCCESS' => 'Все необработанные элементы повторно поставлены в очередь.',

    // Retry-failed action messages (shared)
    'LBL_RETRY_FAILED' => 'Повторить неудачные',
    'LBL_RETRY_FAILED_CONFIRMATION' => 'Вы действительно хотите повторить? Все необработанные элементы будут повторно поставлены в очередь.',
    'LBL_RETRY_FAILED_SUCCESS' => 'Все необработанные элементы повторно поставлены в очередь.',

    // Capability flag field labels
    'LBL_ALLOW_FAILURE_RETRY_ACTION' => 'Разрешить повторную постановку в очередь необработанных элементов',
    'LBL_ALLOW_FAILURE_RERUN_ACTION' => 'Разрешить перезапуск неудавшихся заданий',

    // Subpanel
    'LBL_FAILED_ITEMS' => 'Необработанные элементы',
    'LBL_COMPLETED_ITEMS' => 'Обработанные элементы',
];
