<?php
/*********************************************************************************
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 
 ********************************************************************************/
  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite  ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the SuiteCRM application.
  *********************************************************************************/

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$mod_strings = array (
    'LBL_MODULE_NAME' => 'OAuth2-токены',
    'LBL_MODULE_TITLE' => 'OAuth2-токены',
    'LBL_MODULE_ID'=> 'OAuth2-токены',
	'LBL_TOKEN_ID'=> 'ID токена',
	'LBL_CLIENT'=> 'Клиент',
    'LBL_TOKEN_IS_REVOKED'=> 'Отозван',
    'LBL_ACCESS_TOKEN_TYPE'=> 'Формат токена',
    'LBL_ACCESS_TOKEN_EXPIRES'=> 'Время жизни токена доступа',
    'LBL_REFRESH_TOKEN_EXPIRES'=> 'Время жизни токена обновления',
    'LBL_GRANT_TYPE'=> 'Вид гранта',
    'LBL_SCOPES'=> 'Области',
    'LBL_REVOKE_TOKEN'=> 'Отозвать токен',
    'LBL_REVOKE_TOKENS'=> 'Отзыв токенов', ///
    'LBL_CLIENT_NAME'=> 'Клиент',
    'LBL_USER' => 'Пользователь',
    'LBL_IS_ACTIVE' => 'Отобразить только активные токены',

    'LNK_OAUTH2_TOKEN_LIST'=> 'Токены',
    'LNK_OAUTH2_CLIENT_LIST' => 'OAuth2-клиенты',

    'LNK_NEW_OAUTH2_CLIENT'=> 'Создать OAuth2-клиента',
	'LNK_NEW_OAUTH2_PASSWORD_CLIENT' => 'Добавить доступ по паролю ',
    'LNK_NEW_OAUTH2_CREDENTIALS_CLIENT' => 'Добавить доступ через клиентские полномочия',
    'LNK_NEW_OAUTH2_IMPLICIT_CLIENT' => 'Добавить неявный доступ',
    'LNK_NEW_OAUTH2_AUTHORIZATION_CLIENT' => 'Добавить доступ через код подтверждения',

    'LBL_ACCESS_TOKEN' => 'Токен доступа',
    'LBL_REFRESH_TOKEN' => 'Токен обновления',
);
