<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings['LBL_DEFAULT'] = 'По умолчанию';
$mod_strings['LBL_ADD_LAYOUT'] = 'Добавить макет';
$mod_strings['LBL_ADD_LAYOUTS'] = 'Добавить макет';
$mod_strings['LBL_QUESTION_ADD_LAYOUT'] = 'Выбрать макет Групп для добавления.';
$mod_strings['LBL_REMOVE_LAYOUT'] = 'Удалить макет Групп';

$mod_strings['LBL_SECURITYGROUP'] = 'Группы пользователей:';
$mod_strings['LBL_COPY_FROM'] = 'Копировать из:';
$mod_strings['LBL_ADDLAYOUTDONE'] = 'Сохранённый макет';
$mod_strings['LBL_REMOVELAYOUTDONE'] = 'Удалённый макет';
$mod_strings['LBL_REMOVE_CONFIRM'] = 'Вы действительно уверены?';
$mod_strings['help']['studioWizard']['addLayoutHelp'] = "Для создания макета Групп пользователей выберите соответствующую Группу и макет для копирования.";


?>
