<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_LIST_ID'=> 'ID списка адресатов' ,
'LBL_ID' => 'ID' ,
'LBL_TARGET_TRACKER_KEY'=> 'Присоединённый ключ трекера' ,
'LBL_TARGET_ID'=> 'ID адресата' ,
'LBL_TARGET_TYPE'=> 'Тип адресата' ,
'LBL_ACTIVITY_TYPE' => 'Состояние' ,
'LBL_ACTIVITY_DATE' => 'Дата' ,
'LBL_RELATED_ID' => 'Родительский ID' ,
'LBL_RELATED_TYPE'=> 'Родительский тип' ,
'LBL_DELETED' => 'Удалено' ,
'LBL_MODULE_NAME' => 'Журнал маркет. кампании' ,
'LBL_LIST_RECIPIENT_EMAIL'=> 'E-mail получателя' ,
'LBL_LIST_RECIPIENT_NAME'=> 'Имя получателя' ,
'LBL_ARCHIVED'=> 'Архив' ,
'LBL_HITS'=> 'Хиты' ,

'LBL_CAMPAIGN_NAME' => 'Название:' ,
'LBL_CAMPAIGN' => 'Маркетинговая кампания:' ,
'LBL_NAME' => 'Название: ' ,
'LBL_INVITEE' => 'Контакты' ,
'LBL_LIST_CAMPAIGN_NAME' => 'Маркет. кампания' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LIST_TYPE' => 'Тип' ,
'LBL_LIST_END_DATE' => 'Дата окончания' ,
'LBL_DATE_ENTERED' => 'Дата ввода' ,
'LBL_DATE_MODIFIED' => 'Дата изменения' ,
'LBL_MODIFIED' => 'Исправлено: ' ,
'LBL_CREATED' => 'Создано: ' ,
'LBL_TEAM' => 'Группа: ' ,
'LBL_ASSIGNED_TO' => 'Ответственный(ая): ' ,
'LBL_CAMPAIGN_START_DATE' => 'Дата начала: ' ,
'LBL_CAMPAIGN_END_DATE' => 'Дата окончания: ' ,
'LBL_CAMPAIGN_STATUS' => 'Статус: ' ,
'LBL_CAMPAIGN_BUDGET' => 'Бюджет: ' ,
'LBL_CAMPAIGN_EXPECTED_COST' => 'Ожидаемая стоимость: ' ,
'LBL_CAMPAIGN_ACTUAL_COST' => 'Фактическая стоимость: ' ,
'LBL_CAMPAIGN_EXPECTED_REVENUE' => 'Расчётные поступления: ' ,
'LBL_CAMPAIGN_TYPE' => 'Тип: ' ,
'LBL_CAMPAIGN_OBJECTIVE' => 'Цель: ' ,
'LBL_CAMPAIGN_CONTENT' => 'Описание: ' ,
'LBL_CREATED_LEAD' => 'созданный Предв. контакт',
'LBL_CREATED_CONTACT' => 'созданный Контакт',
'LBL_CREATED_OPPORTUNITY' => 'Созданная Сделка',
'LBL_TARGETED_USER' => 'Созданный Адресат',
'LBL_SENT_EMAIL' => 'Отправленный E-mail',
'LBL_LIST_FORM_TITLE'=> 'Адресуемые маркет. кампании' ,
'LBL_LIST_ACTIVITY_DATE'=> 'Дата мероприятия' ,
'LBL_LIST_CAMPAIGN_OBJECTIVE'=> 'Цель маркет. кампании' ,
'LBL_RELATED'=> 'Относится к' ,
'LBL_CLICKED_URL_KEY'=> 'Ключ выбранной ссылки' ,
'LBL_URL_CLICKED'=> 'Выбранная ссылка ',
'LBL_MORE_INFO'=> 'Подробная информация' ,

'LBL_CAMPAIGNS' => 'Маркет. кампании',
'LBL_LIST_MARKETING_NAME' => 'Маркетинговая кампания',
);
?>
