<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания:',
  'LBL_DATE_MODIFIED' => 'Дата изменения:',
  'LBL_MODIFIED' => 'Изменено:',
  'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
  'LBL_CREATED' => 'Создано:',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалён',
  'LBL_NAME' => 'Счёт',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'ERR_DELETE_RECORD' => 'Вы должны указать номер записи перед удалением.',
  'LBL_ACCOUNT_NAME' => 'Название',
  'LBL_ACCOUNT' => 'Контрагент:',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_ADDRESS_INFORMATION' => 'Адресная информация',
  'LBL_ANNUAL_REVENUE' => 'Годовой доход:',
  'LBL_ANY_ADDRESS' => 'Любой адрес:' ,
  'LBL_ANY_EMAIL' => 'Любой E-mail:' ,
  'LBL_ANY_PHONE' => 'Любой тел.:' ,
  'LBL_RATING' => 'Рейтинг',
  'LBL_ASSIGNED_USER' => 'Ответственный(ая)',
  'LBL_BILLING_ADDRESS_CITY' => 'расчётный адрес - город:',
  'LBL_BILLING_ADDRESS_COUNTRY' => 'расчётный адрес - страна:',
  'LBL_BILLING_ADDRESS_POSTALCODE' => 'расчётный адрес - индекс:' ,
  'LBL_BILLING_ADDRESS_STATE' => 'расчётный адрес - область:' ,
  'LBL_BILLING_ADDRESS_STREET_2' => 'Адрес получателя - улица 2' ,
  'LBL_BILLING_ADDRESS_STREET_3' => 'Адрес получателя - улица 3' ,
  'LBL_BILLING_ADDRESS_STREET_4' => 'Адрес получателя - улица 4' ,
  'LBL_BILLING_ADDRESS_STREET' => 'расчётный адрес - улица:' ,
  'LBL_BILLING_ADDRESS' => 'Расчётный адрес:',
  'LBL_ACCOUNT_INFORMATION' => 'Основная информация',
  'LBL_CITY' => 'Город:',
  'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты',
  'LBL_COUNTRY' => 'Страна:',
  'LBL_DEFAULT_SUBPANEL_TITLE' => 'Контрагенты',
  'LBL_DUPLICATE' => 'Возможно дублирующий контрагент',
  'LBL_EMAIL' => 'E-mail:',
  'LBL_EMPLOYEES' => 'Сотрудники:',
  'LBL_FAX' => 'Факс:',
  'LBL_INDUSTRY' => 'Отрасль:',
  'LBL_LIST_ACCOUNT_NAME' => 'Контрагент',
  'LBL_LIST_CITY' => 'Город',
  'LBL_LIST_EMAIL_ADDRESS' => 'Адрес E-mail',
  'LBL_LIST_PHONE' => 'Тел.' ,
  'LBL_LIST_STATE' => 'Область' ,
  'LBL_MEMBER_OF' => 'Состоит в:',
  'LBL_MEMBER_ORG_SUBPANEL_TITLE' => 'Членские организации' ,
  'LBL_OTHER_EMAIL_ADDRESS' => 'Другой E-mail:' ,
  'LBL_OTHER_PHONE' => 'Другой тел.:' ,
  'LBL_OWNERSHIP' => 'Собственность:' ,
  'LBL_PARENT_ACCOUNT_ID' => 'Родительский контрагент(ID)',
  'LBL_PHONE_ALT' => 'Другой тел.:' ,
  'LBL_PHONE_FAX' => 'Тел. (факс):' ,
  'LBL_PHONE_OFFICE' => 'Тел. (раб.):' ,
  'LBL_PHONE' => 'Тел.:' ,
  'LBL_POSTAL_CODE' => 'Индекс:' ,
  'LBL_SAVE_ACCOUNT' => 'Сохранение контрагента',
  'LBL_SHIPPING_ADDRESS_CITY' => 'Отгрузочный адрес - город:' ,
  'LBL_SHIPPING_ADDRESS_COUNTRY' => 'Отгрузочный адрес - страна:' ,
  'LBL_SHIPPING_ADDRESS_POSTALCODE' => 'Отгрузочный адрес - индекс:' ,
  'LBL_SHIPPING_ADDRESS_STATE' => 'Отгрузочный адрес - область:' ,
  'LBL_SHIPPING_ADDRESS_STREET_2' => 'Адрес отправителя - улица 2' ,
  'LBL_SHIPPING_ADDRESS_STREET_3' => 'Адрес отправителя - улица 3' ,
  'LBL_SHIPPING_ADDRESS_STREET_4' => 'Адрес отправителя - улица 4' ,
  'LBL_SHIPPING_ADDRESS_STREET' => 'Отгрузочный адрес - улица:' ,
  'LBL_SHIPPING_ADDRESS' => 'Отгрузочный адрес:',
  'LBL_STATE' => 'Область:',
  'LBL_TICKER_SYMBOL' => 'Биржевой код:',
  'LBL_TYPE' => 'Тип:' ,
  'LBL_WEBSITE' => 'Сайт:',
  'LNK_ACCOUNT_LIST' => 'Контрагенты' ,
  'LNK_NEW_ACCOUNT' => 'Создать контрагента',
  'MSG_DUPLICATE' => 'Создаваемый вами контрагент возможно дублирует уже имеющуюся запись. Похожие контрагенты показаны ниже. Нажмите кнопку "Сохранить" для продолжения создания нового контрагента или кнопку "Отказаться" для возврата в модуль.' ,
  'MSG_SHOW_DUPLICATES' => 'Создаваемый вами контрагент возможно дублирует уже имеющуюся запись. Похожие контрагенты показаны ниже. Нажмите кнопку "Сохранить" для продолжения создания нового контрагента или кнопку "Отказаться" для возврата в модуль.' ,
  'NTC_DELETE_CONFIRMATION' => 'Вы действительно хотите удалить эту запись?' ,

  'LBL_LIST_FORM_TITLE' => 'Счета',
  'LBL_MODULE_NAME' => 'Счета',
  'LBL_MODULE_TITLE' => 'Счета',
  'LBL_HOMEPAGE_TITLE' => 'Мои счета',
  'LNK_NEW_RECORD' => 'Создать счёт',
  'LNK_LIST' => 'Счета',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск счетов',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_NEW_FORM_TITLE' => 'Создать счёт',
  'LBL_TERMS_C' => 'Условия',
  'LBL_APPROVAL_ISSUE' => 'Детали утверждения',
  'LBL_APPROVAL_STATUS' => 'Статус утверждения',
  'LBL_BILLING_ACCOUNT' => 'Контрагент',
  'LBL_BILLING_CONTACT' => 'Контакт',
  'LBL_EXPIRATION' => 'Действителен до',
  'LBL_INVOICE_NUMBER' => 'Номер счёта',
  'LBL_OPPORTUNITY' => 'Сделка',
  'LBL_TEMPLATE_DDOWN_C' => 'Шаблоны счетов',
  'LBL_STAGE' => 'Стадия предложения',
  'LBL_TERM' => 'Условия оплаты',
  'LBL_SUBTOTAL_AMOUNT' => 'Итого со скидкой',
  'LBL_DISCOUNT_AMOUNT' => 'Скидка',
  'LBL_TAX_AMOUNT' => 'Всего НДС',
  'LBL_SHIPPING_AMOUNT' => 'Доставка',
  'LBL_TOTAL_AMT' => 'Итого без скидки',
  'VALUE' => 'Название',
  'LBL_EMAIL_ADDRESSES' => 'Адреса E-mail',
  'LBL_LINE_ITEMS' => 'Позиции',
  'LBL_GRAND_TOTAL' => 'ВСЕГО К ОПЛАТЕ',
  'LBL_QUOTE_NUMBER' => 'Номер предложения',
  'LBL_QUOTE_DATE' => 'Дата выставления предложения',
  'LBL_INVOICE_DATE' => 'Дата выставления счёта',
  'LBL_DUE_DATE' => 'Крайний срок платежа',
  'LBL_STATUS' => 'Статус',
  'LBL_INVOICE_STATUS' => 'Статус счёта',
  'LBL_PRODUCT_QUANITY' => 'Количество',
  'LBL_PRODUCT_NAME' => 'Товар',
  'LBL_PART_NUMBER' => 'Артикул',
  'LBL_PRODUCT_NOTE' => 'Заметка',
  'LBL_PRODUCT_DESCRIPTION' => 'Описание',
  'LBL_LIST_PRICE' => 'Цена по прайсу',
  'LBL_DISCOUNT_AMT' => 'Скидка',
  'LBL_UNIT_PRICE' => 'Цена за единицу',
  'LBL_TOTAL_PRICE' => 'Итого без НДС',
  'LBL_VAT' => 'НДС (%)',
  'LBL_VAT_AMT' => 'НДС',
  'LBL_ADD_PRODUCT_LINE' => 'Добавить товар',
  'LBL_SERVICE_NAME' => 'Услуга',
  'LBL_SERVICE_LIST_PRICE' => 'Стоимость по прайсу',
  'LBL_SERVICE_PRICE' => 'Конечная стоимость',
  'LBL_SERVICE_DISCOUNT' => 'Скидка',
  'LBL_ADD_SERVICE_LINE' => 'Добавить услугу ',
  'LBL_REMOVE_PRODUCT_LINE' => 'Удалить',
  'LBL_PRINT_AS_PDF' => 'Сохранить в PDF',
  'LBL_EMAIL_INVOICE' => 'Отправить по почте',
  'LBL_LIST_NUM' => '№',
  'LBL_PDF_NAME' => 'Счёт',
  'LBL_EMAIL_NAME' => 'Счёт:',
  'LBL_NO_TEMPLATE' => 'ОШИБКА\nШаблоны счетов не обнаружены.\nЕсли необходимый шаблон счёта отсутствует - откройте модуль PDF-шаблонов и создайте необходимый шаблон.',
  
  'LBL_SUBTOTAL_TAX_AMOUNT' => 'Итого без доставки',//pre shipping
  'LBL_EMAIL_PDF' => 'Отправить по почте в виде PDF',
  
  'LBL_ADD_GROUP' => 'Добавить группу',
  'LBL_DELETE_GROUP' => 'Удалить группу',
  'LBL_GROUP_NAME' => 'Группа',
  'LBL_GROUP_TOTAL' => 'ИТОГО С НДС',

    'LBL_SHIPPING_TAX' => 'НДС доставки (%)',
    'LBL_SHIPPING_TAX_AMT' => 'НДС доставки',
    'LBL_IMPORT_LINE_ITEMS' => 'Импорт позиций',
	
	'LBL_SUBTOTAL_AMOUNT_USDOLLAR' => 'Итого со скидкой (основная валюта)',
    'LBL_DISCOUNT_AMOUNT_USDOLLAR' => 'Скидка (основная валюта)',
    'LBL_TAX_AMOUNT_USDOLLAR' => 'Всего НДС (основная валюта)',
    'LBL_SHIPPING_AMOUNT_USDOLLAR' => 'Доставка (основная валюта)',
    'LBL_TOTAL_AMT_USDOLLAR' => 'Итого без скидки (основная валюта)',
    'LBL_SHIPPING_TAX_AMT_USDOLLAR' => 'НДС доставки (основная валюта)',
    'LBL_GRAND_TOTAL_USDOLLAR' => 'ВСЕГО К ОПЛАТЕ (основная валюта)',
	'LBL_INVOICE_TO' => 'Получатель',
	
	'LBL_AOS_LINE_ITEM_GROUPS' => 'Группы',
    'LBL_AOS_PRODUCT_QUOTES' => 'Предложение-Товары',
    'LBL_AOS_QUOTES_AOS_INVOICES' => 'Предложения : Счета',
);
