<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_ALLOW_ALL'=> 'Все' ,
'LBL_ALLOW_NONE'=> 'Нет' ,
'LBL_ALLOW_OWNER'=> 'Владелец' ,
'LBL_ROLE'=> 'Роль' ,
'LBL_NAME'=> 'Имя' ,
'LBL_DESCRIPTION'=> 'Описание' ,
'LIST_ROLES'=> 'Роли' ,
'LBL_USERS_SUBPANEL_TITLE'=> 'Пользователи' ,
'LIST_ROLES_BY_USER'=> 'Список ролей по пользователям' ,
'LBL_ROLES_SUBPANEL_TITLE'=> 'Роли пользователя' ,
'LBL_SEARCH_FORM_TITLE'=> 'Найти' ,
'LBL_NO_ACCESS'=> 'У Вас нет доступа к данной странице. Свяжитесь с вашим системным администратором для получения соответствующих прав.' ,
'LBL_REDIRECT_TO_HOME'=>'Перенаправление на ГЛАВНУЮ страницу через',
'LBL_SECONDS'=>'секунд',
'LBL_ADDING'=> 'Добавлено для ',
)
?>
