<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = [

 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
 'LBL_NAME' => 'Название',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
 'LBL_LIST_FORM_TITLE' => 'Внешние подключения OAuth',
 'LBL_MODULE_NAME' => 'Внешние подключения OAuth',
 'LBL_MODULE_TITLE' => 'Внешние подключения OAuth',
 'LBL_HOMEPAGE_TITLE' => 'Мои внешние подключения OAuth',
 'LNK_NEW_RECORD' => 'Создать внешнее подключение OAuth',

 'LNK_LIST' => 'Внешние подключения OAuth',
 'LBL_SEARCH_FORM_TITLE' => 'Поиск внешних подключений OAuth',
 'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
 'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
 'LBL_NEW_FORM_TITLE' => 'Новое внешнее подключение OAuth',

 'LBL_LIST_DELETE' => 'Удалить',
 'LBL_TYPE' => 'Тип подключения',

 'LBL_CLIENT_ID' => 'ID клиента',
 'LBL_CLIENT_SECRET' => 'Секрет клиента',
 'LBL_TOKEN_TYPE' => 'Тип токена',
 'LBL_EXPIRES_IN' => 'Действителен до',
 'LBL_ACCESS_TOKEN' => 'Токен доступа',
 'LBL_REFRESH_TOKEN' => 'Токен обновления',
 'LBL_PROVIDER' => 'Провайдер',

 'LBL_AUTHENTICATE' => 'Аутентификация',
	
'LBL_EXTERNAL_OAUTH_PROVIDER' => 'Провайдер',
 'LBL_EXTERNAL_OAUTH_PROVIDER_NAME' => 'Провайдер',
 'LBL_EXTERNAL_OAUTH_PROVIDER_ID' => 'ID Провайдера',

 'LNK_LIST_CREATE_NEW_PERSONAL' => 'Создать персональное подключение OAuth',
 'LNK_LIST_CREATE_NEW_GROUP' => 'Создать групповое подключение OAuth',
 'LNK_LIST_INBOUND_EMAILS' => 'Учётные записи входящей почты',
 'LNK_LIST_OUTBOUND_EMAILS' => 'Учётные записи исходящей почты',
'LNK_LIST_EXTERNAL_OAUTH_PROVIDERS' => 'Внешние провайдеры OAuth',

 'LBL_OWNER' => 'Владелец',
];
