<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_MODULE_NAME'=> 'Календарь' ,
'LBL_AGENDADAY' => 'День',
'LBL_AGENDAWEEK' => 'Неделя',
'LBL_SHAREDWEEK' => 'Сводная неделя',
'LBL_SHAREDMONTH' => 'Сводный месяц',

'LBL_MODULE_TITLE'=> 'Календарь' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_CALL_LIST' => 'Звонки' ,
'LNK_MEETING_LIST' => 'Встречи' ,
'LNK_TASK_LIST' => 'Задачи' ,
'LNK_TASK' => 'Задача',
'LNK_TASK_VIEW' => 'Просмотр задачи',
'LNK_VIEW_CALENDAR' => 'Сегодня' ,
'LNK_IMPORT_CALLS'=> 'Импорт звонков',
'LNK_IMPORT_MEETINGS'=> 'Импорт встреч',
'LNK_IMPORT_TASKS'=> 'Импорт задач',
'LBL_MONTH' => 'Месяц' ,

'LBL_YEAR' => 'Год' ,

'LBL_PREVIOUS_MONTH' => 'Предыдущий месяц' ,
'LBL_PREVIOUS_DAY' => 'Предыдущий день' ,
'LBL_PREVIOUS_YEAR' => 'Предыдущий год' ,
'LBL_PREVIOUS_WEEK' => 'Предыдущая неделя' ,
'LBL_NEXT_MONTH' => 'Следующий месяц' ,
'LBL_NEXT_DAY' => 'Следующий день' ,
'LBL_NEXT_YEAR' => 'Следующий год' ,
'LBL_NEXT_WEEK' => 'Следующая неделя' ,
'LBL_AM' => 'AM',
'LBL_PM' => 'PM',
'LBL_SCHEDULED' => 'Запланировано' ,
'LBL_BUSY' => 'Занято' ,
'LBL_CONFLICT' => 'Конфликт' ,
'LBL_USER_CALENDARS' => 'Пользовательские календари' ,
'LBL_SHARED' => 'Сводный' ,
'LBL_PREVIOUS_SHARED' => 'Пред.' ,
'LBL_NEXT_SHARED' => 'След.' ,
'LBL_SHARED_CAL_TITLE' => 'Сводный календарь' ,
'LBL_USERS' => 'Пользователи' ,
'LBL_REFRESH' => 'Обновить' ,
'LBL_EDIT_USERLIST' => 'Выбор пользователей',
'LBL_SELECT_USERS' => 'Просмотр календарей выбранных пользователей' ,
'LBL_FILTER_BY_TEAM' => 'Фильтрация списка пользователей по группам:' ,
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_DATE' => 'Начальные дата и время',
'LBL_CREATE_MEETING' => 'Назначить встречу',
'LBL_CREATE_CALL' => 'Назначить звонок',  
'LBL_HOURS_ABBREV' => 'час.',
'LBL_MINS_ABBREV' => 'мин.',

'LBL_YES' => 'Да',
'LBL_NO' => 'Нет',
'LBL_SETTINGS' => 'Настройка календаря',
'LBL_CREATE_NEW_RECORD' => 'Назначить мероприятие',
'LBL_LOADING' => 'Загрузка ......',
'LBL_SAVING' => 'Сохранение ......',
'LBL_SENDING_INVITES' => 'Сохранение и отправка приглашений .....',
'LBL_CONFIRM_REMOVE' => 'Вы действительно хотите удалить эту запись?',
'LBL_CONFIRM_REMOVE_ALL_RECURRING' => 'Вы действительно хотите удалить все записи о данном мероприятии, включая повторные?', 
'LBL_EDIT_RECORD' => 'Редактирование мероприятия',
'LBL_ERROR_SAVING' => 'В процессе сохранения произошла ошибка',
'LBL_ERROR_LOADING' => 'В процессе загрузки произошла ошибка',
'LBL_GOTO_DATE' => 'Перейти на дату',
'NOTICE_DURATION_TIME' => 'Время продолжительности должно быть больше нуля',
'LBL_STYLE_BASIC' => 'Основной',
'LBL_STYLE_ADVANCED' => 'Расширенный',

'LBL_INFO_TITLE' => 'Подробности',
'LBL_INFO_DESC' => 'Описание',
'LBL_INFO_START_DT' => 'Дата начала',
'LBL_INFO_DUE_DT' => 'Дата завершения',
'LBL_INFO_DURATION' => 'Продолжительность',
'LBL_INFO_NAME' => 'Тема',
'LBL_INFO_RELATED_TO' => 'Связано с',

'LBL_NO_USER' => 'Нет совпадений для поля: Ответственный(ая)',
'LBL_SUBJECT' => 'Тема',
'LBL_DURATION' => 'Продолжительность',
'LBL_STATUS' => 'Статус',
'LBL_PRIORITY' => 'Приоритет',
'LBL_DATE_TIME' => 'Дата и время',


'LBL_SETTINGS_TITLE' => 'Настройка календаря',
'LBL_SETTINGS_DISPLAY_TIMESLOTS' => 'Разделять сутки на временные интервалы:', 
'LBL_SETTINGS_TIME_STARTS'=>'Время начала:', 
'LBL_SETTINGS_TIME_ENDS'=>'Время завершения:', 
'LBL_SETTINGS_CALLS_SHOW' => 'Отображать звонки:',
'LBL_SETTINGS_TASKS_SHOW' => 'Отображать задачи:', 
'LBL_SETTINGS_COMPLETED_SHOW' => 'Отображать завершённые мероприятия:',
'LBL_SETTINGS_DISPLAY_SHARED_CALENDAR_SEPARATE' => 'Разделённый сводный календарь:',
	
'LBL_SAVE_BUTTON' => 'Сохранить',
'LBL_DELETE_BUTTON' => 'Удалить',
'LBL_APPLY_BUTTON' => 'Применить',
'LBL_SEND_INVITES' => 'Сохранить и отправить приглашения',
'LBL_CANCEL_BUTTON' => 'Отказаться',
'LBL_CLOSE_BUTTON' => 'Закрыть',

'LBL_GENERAL_TAB' => 'Основное',
'LBL_PARTICIPANTS_TAB' =>'Участники',
'LBL_REPEAT_TAB' => 'Повторы',	
	
'LBL_REPEAT_TYPE' => 'Повторять', 
'LBL_REPEAT_INTERVAL' => 'Каждые',
'LBL_REPEAT_END' => 'Прекратить',	
'LBL_REPEAT_END_AFTER' => 'после',
'LBL_REPEAT_OCCURRENCES' => 'повторов',
'LBL_REPEAT_END_BY' => '',	
'LBL_REPEAT_DOW' => 'Дни повторов',	
'LBL_REPEAT_UNTIL' => 'Повторять до',
'LBL_REPEAT_COUNT' => 'Число повторов',
'LBL_REPEAT_LIMIT_ERROR' => 'Вы пытаетесь создать более $limit встреч.',
'LBL_EDIT_ALL_RECURRENCES' => 'Править, включая повторы',
'LBL_REMOVE_ALL_RECURRENCES' => 'Удалить, включая повторы',
'LBL_DATE_END_ERROR' => 'Дата начала не может быть позже даты окончания', 
'ERR_YEAR_BETWEEN' => 'Календарь не может отобразить запрашиваемый год. <br>Значение должно быть в интервале от 1970 до 2037 года.',
'ERR_NEIGHBOR_DATE' => 'get_neighbor_date_str: not defined for this view',
'LBL_NO_ITEMS_MOBILE' => 'На эту неделю не назначено ни одного мероприятия.',
'LBL_GENERAL_SETTINGS' => 'Настройки',
'LBL_COLOR_SETTINGS' => 'Настройки цветовой схемы',
'LBL_MODULE' => 'Модуль',
'LBL_BODY' => 'Фон',
'LBL_BORDER' => 'Граница',
'LBL_TEXT' => 'Текст',

);

$mod_list_strings = array(
	
'dom_cal_weekdays'=>
array(
'Вс',
'Пн',
'Вт',
'Ср',
'Чт',
'Пт',
'Сб',
),
'dom_cal_weekdays_long'=>
array(
'Воскресенье',
'Понедельник',
'Вторник',
'Среда',
'Четверг',
'Пятница',
'Суббота',
),
'dom_cal_month'=>
array(
'',
'Янв',
'Фев',
'Мар',
'Апр',
'Май',
'Июн',
'Июл',
'Авг',
'Сен',
'Окт',
'Ноя',
'Дек',
),
'dom_cal_month_long'=>
array(
'',
'Январь',
'Февраль',
'Март',
'Апрель',
'Май',
'Июнь',
'Июль',
'Август',
'Сентябрь',
'Октябрь',
'Ноябрь',
'Декабрь',
),
);
?>
