<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_MODULE_NAME' => 'Роли',
'LBL_MODULE_TITLE' => 'Роли - Главная',
'LBL_ROLE'=> 'Роль' ,
'LBL_NAME'=> 'Название' ,
'LBL_DESCRIPTION'=> 'Описание' ,
'LIST_ROLES'=> 'Роли' ,
'LBL_USERS_SUBPANEL_TITLE'=> 'Пользователи' ,
'LIST_ROLES_BY_USER'=> 'Список ролей по пользователям' ,
'LBL_LIST_FORM_TITLE' => 'Роли',
'LBL_ROLES_SUBPANEL_TITLE'=> 'Роли пользователя' ,
'LBL_SEARCH_FORM_TITLE'=> 'Найти' ,
'LBL_CREATE_ROLE'=> 'Создать роль' ,
'LBL_EDIT_VIEW_DIRECTIONS'=> 'Нажмите два раза на элементе для изменения значения.'  ,
'LBL_ACCESS_DEFAULT'=> 'По умолчанию',
'LBL_ACTION_ADMIN'=> 'Тип доступа',
'LBL_ALL'=> 'Все',
'LBL_DUPLICATE_OF'=> 'Дублирует ',
)
?>
