<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
  
$mod_strings['LBL_ASSIGNED_TO_ID'] = 'Ответственный(ая)';
$mod_strings['LBL_ASSIGNED_TO_NAME'] = 'Ответственный(ая)';
$mod_strings['LBL_ID'] = 'ID';
$mod_strings['LBL_DATE_ENTERED'] = 'Создано';
$mod_strings['LBL_DATE_MODIFIED'] = 'Изменено';
$mod_strings['LBL_MODIFIED'] = 'Изменено';
$mod_strings['LBL_MODIFIED_ID'] = 'Изменено(ID)';
$mod_strings['LBL_MODIFIED_NAME'] = 'Изменено (Имя)';
$mod_strings['LBL_CREATED'] = 'Создано';
$mod_strings['LBL_CREATED_ID'] = 'Создано(ID)';
$mod_strings['LBL_DESCRIPTION'] = 'Описание';
$mod_strings['LBL_DELETED'] = 'Удалено';
$mod_strings['LBL_NAME'] = 'Участок карты';
$mod_strings['LBL_CREATED_USER'] = 'Создано';
$mod_strings['LBL_MODIFIED_USER'] = 'Изменено';
$mod_strings['LBL_LIST_NAME'] = 'Участок карты';
$mod_strings['LBL_LIST_FORM_TITLE'] = 'Участки карт';
$mod_strings['LBL_MODULE_NAME'] = 'Участки карт';
$mod_strings['LBL_MODULE_TITLE'] = 'Участки карт';
$mod_strings['LBL_HOMEPAGE_TITLE'] = 'Мои Участки карт';
$mod_strings['LNK_NEW_RECORD'] = 'Создать участок';
$mod_strings['LNK_LIST'] = 'Участки карт';
$mod_strings['LNK_IMPORT_JJWG_AREAS'] = 'Импорт участков карт';
$mod_strings['LBL_SEARCH_FORM_TITLE'] = 'Поиск участков карт';
$mod_strings['LBL_HISTORY_SUBPANEL_TITLE'] = 'История';
$mod_strings['LBL_ACTIVITIES_SUBPANEL_TITLE'] = 'Мероприятия';
$mod_strings['LBL_JJWG_AREAS_SUBPANEL_TITLE'] = 'Участки карт';
$mod_strings['LBL_NEW_FORM_TITLE'] = 'Новый участок карты';
$mod_strings['LBL_CITY'] = 'Город';
$mod_strings['LBL_STATE'] = 'Область';
$mod_strings['LBL_COUNTRY'] = 'Страна';
$mod_strings['LBL_COORDINATES'] = 'Координаты';
$mod_strings['LBL_LIST_ASSIGNED_USER'] = 'Ответственный(ая)';
$mod_strings['LBL_AREA_MAP'] = 'Area Map';

$mod_strings['LBL_AREA_EDIT_TITLE'] = 'Обозначение границ участка:';
$mod_strings['LBL_AREA_EDIT_DESC_1'] = 'Укажите метки, обозначающие границу участка карты.';
$mod_strings['LBL_AREA_EDIT_DESC_2'] = 'Для завершения нажмите на первую установленную метку.';
$mod_strings['LBL_AREA_EDIT_RESET'] = 'Сбросить';
$mod_strings['LBL_AREA_EDIT_USE_AREA_COORDINATES'] = 'Использовать координаты участка карты';
$mod_strings['LBL_AREA_EDIT_COORDINATE_RESULTS'] = 'Формат данных: широта, долгота, высота над уровнем моря.';
$mod_strings['LBL_JJWG_MAPS_JJWG_AREAS_FROM_JJWG_MAPS_TITLE'] = 'Карты';

?>