<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_ID' => 'ID отношения' ,
'LBL_RELATIONSHIP_NAME' => 'Название отношения' ,
'LBL_LHS_MODULE' => 'Название модуля LHS' ,
'LBL_LHS_TABLE' => 'Название таблицы LHS' ,
'LBL_LHS_KEY' => 'Название ключа LHS' ,
'LBL_RHS_MODULE' => 'Название модуля RHS' ,
'LBL_RHS_TABLE' => 'Название таблицы RHS' ,
'LBL_RHS_KEY' => 'Название ключа RHS' ,
'LBL_JOIN_TABLE' => 'Название присоединённой таблицы' ,
'LBL_JOIN_KEY_LHS' => 'Ключ присоединения LHS' ,
'LBL_JOIN_KEY_RHS' => 'Ключ присоединения RHS' ,
'LBL_RELATIONSHIP_TYPE' => 'Тип отношения' ,
'LBL_RELATIONSHIP_ROLE_COLUMN' => 'Название столбца роли отношения' ,
'LBL_RELATIONSHIP_ROLE_COLUMN_VALUE' => 'Значение столбца роли отношения' ,
'LBL_REVERSE' => 'Обратить' ,
'LBL_DELETED' => 'Удалено' ,
);

?>
