<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_ID' => 'Изменено(ID)',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_CREATED_ID' => 'Создано(ID)',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Учётная запись для исходящей почты',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Серверы исходящей почты',
  'LBL_MODULE_NAME' => 'Серверы исходящей почты (SMTP)',
  'LBL_MODULE_TITLE' => 'Серверы исходящей почты (SMTP)',
  'LBL_HOMEPAGE_TITLE' => 'Мои серверы исходящей почты',
  'LNK_NEW_RECORD' => 'Добавить сервер исходящей почты',
  'LNK_LIST' => 'Перечень серверов исходящей почты',
  'LNK_IMPORT_OUTBOUNDEMAILACCOUNT' => 'Импорт данных о серверах исходящей почты',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск серверов исходящей почты',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_OUTBOUNDEMAILACCOUNT_SUBPANEL_TITLE' => 'Серверы исходящей почты',
  'LBL_NEW_FORM_TITLE' => 'Серверы исходящей почты',
  'LBL_USERNAME' => 'Логин',
  'LBL_PASSWORD' => 'Пароль',
  'LBL_SMTP_SERVERNAME' => 'Имя сервера SMTP',
  'LBL_SMTP_AUTH' => 'Аутентификация',
  'LBL_SMTP_PORT' => 'Порт',
  'LBL_SMTP_PROTOCOL' => 'Протокол',
  'LBL_EDITVIEW_PANEL1' => 'Параметры сервера SMTP',
  'LNK_IMPORT_OUTBOUNDEMAILACCOUNTS' => 'Импорт данных о серверах исходящей почты',
  'LBL_OUTBOUNDEMAILACCOUNTS_SUBPANEL_TITLE' => 'Серверы исходящей почты',
  'LBL_OUTBOUNDEMAILACCOUNT_CAMPA' => 'outboundemailaccount_campaigns_name',
  'LBL_CHANGE_PASSWORD' => 'Изменить пароль',
  'LBL_CHOOSE_EMAIL_PROVIDER' => 'Укажите провайдера электронной почты',
  'LBL_SEND_TEST_EMAIL' => 'Тестирование',

    // for outbound email dialog
    'LBL_SMTP_SERVER_HELP' => 'SMTP-сервер может быть использован для отправки исходящей почты. В параметрах учётной записи укажите соответствующие логин и пароль.',
    'LBL_MISSING_DEFAULT_OUTBOUND_SMTP_SETTINGS' => 'Невозможно отправить тестовое письмо: почтовый сервер для отправки исходящей почты не настроен.',
    'LBL_MAIL_SMTPAUTH_REQ'				=> 'Использовать SMTP-аутентификацию?',
    'LBL_MAIL_SMTPPASS'					=> 'Пароль:',
    'LBL_MAIL_SMTPPORT'					=> 'Порт:',
    'LBL_MAIL_SMTPSERVER'				=> 'SMTP-сервер:',
    'LBL_MAIL_SMTPUSER'					=> 'Логин:',
    'LBL_MAIL_SMTPTYPE'                 => 'Тип сервера:',
    'LBL_MAIL_SMTP_SETTINGS'            => 'Параметры SMTP-сервера',
    'LBL_YAHOOMAIL_SMTPPASS'			=> 'Пароль:',
    'LBL_YAHOOMAIL_SMTPUSER'			=> 'Mail ID:',
    'LBL_GMAIL_SMTPPASS'					=> 'Пароль:',
    'LBL_GMAIL_SMTPUSER'					=> 'Логин:',
    'LBL_EXCHANGE_SMTPPASS'					=> 'Пароль:',
    'LBL_EXCHANGE_SMTPUSER'					=> 'Логин:',
    'LBL_EXCHANGE_SMTPPORT'					=> 'Порт:',
    'LBL_EXCHANGE_SMTPSERVER'				=> 'SMTP-сервер:',
);