<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array(
 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Название',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Серверы исходящей почты',
  'LBL_MODULE_NAME' => 'Серверы исходящей почты (SMTP)',
  'LBL_MODULE_TITLE' => 'Серверы исходящей почты (SMTP)',
  'LBL_HOMEPAGE_TITLE' => 'Мои серверы исходящей почты',
  'LNK_NEW_RECORD' => 'Добавить сервер исходящей почты',
  
  'LNK_LIST_CREATE_NEW_PERSONAL' => 'Создать персональную учётную запись исходящей почты',
  'LNK_LIST_CREATE_NEW_GROUP' => 'Создать групповую учётную запись исходящей почты',
  'LNK_LIST_CREATE_SYSTEM_OVERRIDE_GROUP' => 'New System Override Outbound Email Account', ///
	
  'LNK_LIST' => 'Учётные записи исходящей почты',
  'LNK_LIST_INBOUND_EMAIL_ACCOUNTS' => 'Учётные записи входящей почты',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск серверов исходящей почты',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_NEW_FORM_TITLE' => 'Серверы исходящей почты',
  'LBL_USERNAME' => 'Логин',
  'LBL_PASSWORD' => 'Пароль',
  'LBL_SMTP_SERVERNAME' => 'Имя SMTP-сервера',
  'LBL_SMTP_AUTH' => 'Аутентификация',
  'LBL_SMTP_PORT' => 'Порт',
  'LBL_SMTP_PROTOCOL' => 'Протокол',
  'LBL_EDITVIEW_PANEL1' => 'Параметры SMTP-сервера',
  'LBL_OUTBOUND_CONFIGURATION' => 'Настройки исходящей почты',
  'LBL_CONNECTION_CONFIGURATION' => 'Настройки сервера',
  'LBL_CHANGE_PASSWORD' => 'Изменить пароль',
  'LBL_SEND_TEST_EMAIL' => 'Тестирование',

    // for outbound email dialog
    'LBL_MISSING_DEFAULT_OUTBOUND_SMTP_SETTINGS' => 'Невозможно отправить тестовое письмо: почтовый сервер для отправки исходящей почты не настроен.',
    'LBL_MAIL_SMTPAUTH_REQ' => 'Использовать SMTP-аутентификацию?',
    'LBL_MAIL_SMTPPASS' => 'Пароль:',
    'LBL_MAIL_SMTPPORT' => 'Порт:',
    'LBL_MAIL_SMTPSERVER' => 'Сервер исходящей почты:',
    'LBL_MAIL_SMTPUSER' => 'Логин:',
    'LBL_MAIL_SMTP_SETTINGS' => 'Параметры SMTP-сервера',
    'LBL_CHOOSE_EMAIL_PROVIDER' => 'Укажите провайдера электронной почты',
	'LBL_YAHOOMAIL_SMTPPASS' => 'Пароль:',
    'LBL_YAHOOMAIL_SMTPUSER' => 'Mail ID:',
    'LBL_GMAIL_SMTPPASS' => 'Пароль:',
    'LBL_GMAIL_SMTPUSER' => 'Логин:',
    'LBL_EXCHANGE_SMTPPASS' => 'Пароль:',
    'LBL_EXCHANGE_SMTPUSER' => 'Логин:',
    'LBL_EXCHANGE_SMTPPORT' => 'Порт:',
    'LBL_EXCHANGE_SMTPSERVER' => 'SMTP-сервер:',
	
	'LBL_TYPE' => 'Тип учётной записи:',
    'LBL_MAIL_SENDTYPE' => 'Отправка почты с помощью:',
    'LBL_MAIL_SMTPSSL' => 'Параметры SMTP/SSL:',
	'LBL_SMTP_FROM_NAME' => 'Имя отправителя',
    'LBL_SMTP_FROM_ADDR' => 'Адрес отправителя',
	'LBL_REPLY_TO_NAME' => 'Ответить на имя',
    'LBL_REPLY_TO_ADDR' => 'Ответить на адрес',
	
	'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => 'Группы пользователей',

    'LBL_OWNER' => 'Владелец',
    'LBL_OWNER_NAME' => 'Владелец',

    'LNK_EXTERNAL_OAUTH_CONNECTIONS' => 'Внешние подключения OAuth'
);
