<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--


$app_list_strings['moduleList']['AOR_Reports'] = 'Отчёты';
$app_list_strings['moduleList']['AOR_Conditions'] = 'Условия отчёта';
$app_list_strings['moduleList']['AOR_Charts'] = 'Диаграммы отчёта';
$app_list_strings['moduleList']['AOR_Fields'] = 'Поля отчёта';
$app_list_strings['moduleList']['AOR_Scheduled_Reports'] = 'Отчёты по расписанию';
$app_list_strings['aor_operator_list']['Equal_To'] = 'Равно';
$app_list_strings['aor_operator_list']['Not_Equal_To'] = 'НЕ равно';
$app_list_strings['aor_operator_list']['Greater_Than'] = 'Больше';
$app_list_strings['aor_operator_list']['Less_Than'] = 'Меньше';
$app_list_strings['aor_operator_list']['Greater_Than_or_Equal_To'] = 'Больше или равно';
$app_list_strings['aor_operator_list']['Less_Than_or_Equal_To'] = 'Меньше или равно';

$app_list_strings['aor_sql_operator_list']['Equal_To'] = '=';
$app_list_strings['aor_sql_operator_list']['Not_Equal_To'] = '!=';
$app_list_strings['aor_sql_operator_list']['Greater_Than'] = '>';
$app_list_strings['aor_sql_operator_list']['Less_Than'] = '<';
$app_list_strings['aor_sql_operator_list']['Greater_Than_or_Equal_To'] = '>=';
$app_list_strings['aor_sql_operator_list']['Less_Than_or_Equal_To'] = '<=';

$app_list_strings['aor_condition_operator_list']['And'] = 'И';
$app_list_strings['aor_condition_operator_list']['OR'] = 'ИЛИ';

$app_list_strings['aor_condition_type_list']['Value'] = 'Значение';
$app_list_strings['aor_condition_type_list']['Field'] = 'Поле';
$app_list_strings['aor_condition_type_list']['Date'] = 'Дата';
$app_list_strings['aor_condition_type_list']['Multi'] = 'Мультивыбор';

$app_list_strings['aor_date_type_list'][''] = '';
$app_list_strings['aor_date_type_list']['minute'] = 'мин.';
$app_list_strings['aor_date_type_list']['hour'] = 'час.';
$app_list_strings['aor_date_type_list']['day'] = 'дн.';
$app_list_strings['aor_date_type_list']['week'] = 'нед.';
$app_list_strings['aor_date_type_list']['month'] = 'мес.';
$app_list_strings['aor_date_type_list']['business_hours'] = 'рабочих часов';

$app_list_strings['aor_date_options']['now'] = 'Сейчас';
$app_list_strings['aor_date_options']['field'] = 'Это поле';

$app_list_strings['aor_date_operator']['now'] = '';
$app_list_strings['aor_date_operator']['plus'] = '+';
$app_list_strings['aor_date_operator']['minus'] = '-';
$app_list_strings['aor_sort_operator'][''] = '';
$app_list_strings['aor_sort_operator']['ASC'] = 'Восходящая';
$app_list_strings['aor_sort_operator']['DESC'] = 'Нисходящая';

$app_list_strings['aor_function_list'][''] = '';
$app_list_strings['aor_function_list']['COUNT'] = 'КОЛИЧЕСТВО';
$app_list_strings['aor_function_list']['MIN'] = 'МИНИМУМ';
$app_list_strings['aor_function_list']['MAX'] = 'МАКСИМУМ';
$app_list_strings['aor_function_list']['SUM'] = 'СУММА';
$app_list_strings['aor_function_list']['AVG'] = 'СРЕДНЕЕ';

$app_list_strings['aor_total_options'][''] = '';
$app_list_strings['aor_total_options']['COUNT'] = 'КОЛИЧЕСТВО';
$app_list_strings['aor_total_options']['SUM'] = 'СУММА';
$app_list_strings['aor_total_options']['AVG'] = 'СРЕДНЕЕ';

$app_list_strings['aor_chart_types']['bar'] = 'Линейчатая диаграмма';
$app_list_strings['aor_chart_types']['line'] = 'График';
$app_list_strings['aor_chart_types']['pie'] = 'Круговая диаграмма';
$app_list_strings['aor_chart_types']['radar'] = 'Лепестковая диаграмма';
$app_list_strings['aor_chart_types']['polar'] = 'Полярная диаграмма';
$app_list_strings['aor_scheduled_report_schedule_types']['monthly'] = 'Ежемесячно';
$app_list_strings['aor_scheduled_report_schedule_types']['weekly'] = 'Еженедельно';
$app_list_strings['aor_scheduled_report_schedule_types']['daily'] = 'Ежедневно';
$app_list_strings['aor_scheduled_reports_status_dom']['active'] = 'Активен';
$app_list_strings['aor_scheduled_reports_status_dom']['inactive'] = 'Не активен';
$app_list_strings['aor_email_type_list']['Email Address'] = 'E-mail';
$app_list_strings['aor_email_type_list']['Specify User'] = 'Пользователь';
$app_list_strings['aor_email_type_list']['Users'] = 'Пользователи';
$app_list_strings['aor_assign_options']['all'] = 'ВСЕ пользователи'; ///
$app_list_strings['aor_assign_options']['role'] = 'ВСЕ пользователи из Роли'; ///
$app_list_strings['aor_assign_options']['security_group'] = 'ВСЕ пользователи из Группы'; ///
$app_strings['LBL_CRON_ON_THE_MONTHDAY'] = '';
$app_strings['LBL_CRON_ON_THE_WEEKDAY'] = '';
$app_strings['LBL_CRON_AT'] = 'в';
$app_strings['LBL_CRON_RAW'] = 'Crontab-нотация';
$app_strings['LBL_CRON_MIN'] = 'Мин.';
$app_strings['LBL_CRON_HOUR'] = 'Час';
$app_strings['LBL_CRON_DAY'] = 'День';
$app_strings['LBL_CRON_MONTH'] = 'Месяц';
$app_strings['LBL_CRON_DOW'] = 'День недели';
$app_strings['LBL_CRON_DAILY'] = 'Ежедневно';
$app_strings['LBL_CRON_WEEKLY'] = 'Еженедельно';
$app_strings['LBL_CRON_MONTHLY'] = 'Ежемесячно';