<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$app_strings['LBL_QUICK_ACCOUNT'] = 'Создать контрагента';
$app_strings['LBL_QUICK_CONTACT'] = 'Создать контакт';
$app_strings['LBL_QUICK_OPPORTUNITY'] = 'Создать сделку';
$app_strings['LBL_QUICK_LEAD'] = 'Создать предварит. контакт';
$app_strings['LBL_QUICK_DOCUMENT'] = 'Создать документ';
$app_strings['LBL_QUICK_CALL'] = 'Назначить звонок';
$app_strings['LBL_QUICK_TASK'] = 'Создать задачу';
$app_strings['LBL_COLLECTION_TYPE'] = 'Модуль';

$app_strings['LBL_ADD_TAB'] = 'Добавить страницу';
$app_strings['LBL_SUITE_DASHBOARD'] = 'Suite - основная страница';
$app_strings['LBL_ENTER_DASHBOARD_NAME'] = 'Название страницы:';
$app_strings['LBL_NUMBER_OF_COLUMNS'] = 'Количество колонок на странице:';
$app_strings['LBL_DELETE_DASHBOARD1'] = 'Вы действительно хотите удалить страницу';
$app_strings['LBL_DELETE_DASHBOARD2'] = '?';
$app_strings['LBL_ADD_DASHBOARD_PAGE'] = 'Добавление новой страницы на закладку ГЛАВНАЯ';
$app_strings['LBL_DELETE_DASHBOARD_PAGE'] = 'Удаление текущей страницы с закладки ГЛАВНАЯ';
$app_strings['LBL_RENAME_DASHBOARD_PAGE'] = 'Переименование страницы';

$app_strings['LBL_DISCOVER_SUITECRM'] = 'Discover SuiteCRM';

$app_list_strings['collection_temp_list'] = array ( 'Tasks' => 'Задачи', 'Meetings' => 'Встречи', 'Calls' => 'Звонки', 'Notes' => 'Заметки', 'Emails' => 'E-mail' );
