<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$app_list_strings['moduleList']['FP_events'] = 'События';
$app_list_strings['moduleList']['FP_Event_Locations'] = 'Места';
$app_list_strings['invite_template_list'][''] = '';

$app_list_strings['fp_event_invite_status_dom']['Invited'] = 'Приглашён';
$app_list_strings['fp_event_invite_status_dom']['Not Invited'] = 'Не приглашён';
$app_list_strings['fp_event_invite_status_dom']['Attended'] = 'Участвовал';
$app_list_strings['fp_event_invite_status_dom']['Not Attended'] = 'Не участвовал';
$app_list_strings['fp_event_status_dom']['Accepted'] = 'Принято';
$app_list_strings['fp_event_status_dom']['Declined'] = 'Отклонено';
$app_list_strings['fp_event_status_dom']['No Response'] = 'Ответ не получен';

$app_strings['LBL_STATUS_EVENT'] = 'Статус приглашения';
$app_strings['LBL_ACCEPT_STATUS'] = 'Статус приглашения';
$app_strings['LBL_LISTVIEW_OPTION_CURRENT'] = 'Текущая страница';
$app_strings['LBL_LISTVIEW_OPTION_ENTIRE'] = 'Все записи';
$app_strings['LBL_LISTVIEW_NONE'] = 'Отменить выбор';