<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--


$app_list_strings['moduleList']['AOP_AOP_Case_Events'] = 'События обращения';
$app_list_strings['moduleList']['AOP_AOP_Case_Updates'] = 'Обновления обращения';
$app_list_strings['moduleList']['AOP_Case_Events'] = 'События обращения';
$app_list_strings['moduleList']['AOP_Case_Updates'] = 'Обновления обращения';
$app_strings['LBL_AOP_EMAIL_REPLY_DELIMITER'] = '========== Пожалуйста, пишите ответ выше этой линии ==========';

$app_list_strings['case_state_dom'] =
  array (
      'Open' => 'Открыто',
      'Closed' => 'Закрыто',
  );
$app_list_strings['case_state_default_key'] = 'Open';
$app_list_strings['case_status_default_key'] = 'Open_New';
$app_list_strings['case_status_dom'] =
  array (
      'Open_New' => 'Новое',
      'Open_Assigned' => 'Назначенное',
      'Closed_Closed' => 'Закрытое',
      'Open_Pending Input' => 'Ожидание решения',
      'Closed_Rejected' => 'Отклонённое',
      'Closed_Duplicate' => 'Продублированное',
  );
  
  $app_list_strings['contact_portal_user_type_dom'] =
    array (
        'Single' => 'Указанный пользователь',
        'Account' => 'Учётная запись пользователя',
    ); 
	
	$app_list_strings['dom_email_distribution_for_auto_create']=array (
    'AOPDefault' => 'Стандартный',
    'singleUser' => 'Указанный пользователь',
    'roundRobin' => 'В цикле',
    'leastBusy' => 'Наименее занятой',
    'random' => 'Случайный',
);