<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings['LBL_JJWG_MAPS_ADMIN_HEADER'] = 'Карты Google';
$mod_strings['LBL_JJWG_MAPS_ADMIN_DESC'] = 'Управление геокодированием, тестирование геокодирования, просмотр результатов геокодирования, настройка параметров карт';
$mod_strings['LBL_JJWG_MAPS_ADMIN_CONFIG_TITLE'] = 'Настройка карт Google';
$mod_strings['LBL_JJWG_MAPS_ADMIN_CONFIG_DESC'] = 'Настройка параметров карт Google';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODED_COUNTS_TITLE'] = 'Результаты геокодирования';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODED_COUNTS_DESC'] = 'Просмотр статистики геокодирования, данные по каждому модулю сгруппированы в зависимости от полученных результатов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_DONATE_TITLE'] = 'Поддержка проекта';
$mod_strings['LBL_JJWG_MAPS_ADMIN_DONATE_DESC'] = ' ';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODE_ADDRESSES_TITLE'] = 'Геокодирование адресов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODE_ADDRESSES_DESC'] = 'Геокодирование адресов системы, этот процесс может занять продолжительное время!';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODING_TEST_TITLE'] = 'Тестирование геокодирования';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODING_TEST_DESC'] = 'Запуск геокодирования введённого адреса с детальным просмотром результатов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_ADDRESS_CACHE_TITLE'] = 'Кэш адресов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_ADDRESS_CACHE_DESC'] = 'Доступ к кэшу адресов. Обратите внимание: это только кэш!';
