<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings['LBL_SALESAGILITY_ADMIN'] = 'OpenAdmin';
$mod_strings['LBL_AOS_ADMIN_CONTRACT_SETTINGS'] = 'Параметры договоров';
$mod_strings['LBL_AOS_ADMIN_CONTRACT_RENEWAL_REMINDER'] = 'Период действия договора';
$mod_strings['LBL_AOS_ADMIN_MANAGE_AOS'] = 'Параметры модулей продаж';
$mod_strings['LBL_AOS_ADMIN_INVOICE_SETTINGS'] = 'Параметры счетов';
$mod_strings['LBL_AOS_ADMIN_INITIAL_INVOICE_NUMBER'] = 'Начинать нумерацию с';
$mod_strings['LBL_AOS_ADMIN_QUOTE_SETTINGS'] = 'Параметры предложений';
$mod_strings['LBL_AOS_ADMIN_INITIAL_QUOTE_NUMBER'] = 'Начинать нумерацию с';
$mod_strings['LBL_AOS_ADMIN_LINE_ITEM_SETTINGS'] = 'Настройка позиций в бланках';
$mod_strings['LBL_AOS_ADMIN_ENABLE_LINE_ITEM_GROUPS'] = 'Возможность группировки позиций';
$mod_strings['LBL_AOS_ADMIN_ENABLE_LINE_ITEM_TOTAL_TAX'] = 'Включать НДС в сумму<br>(для каждой позиции)';
$mod_strings['LBL_AOS_SETTINGS'] = 'Настройка модулей продаж';
$mod_strings['LBL_AOS_PRODUCTS'] = 'AOS Products'; ///
$mod_strings['LBL_AOS_EDIT'] = 'edit'; ///
$mod_strings['LBL_AOS_DAYS'] = 'дней';
$mod_strings['LBL_CHANGE_SETTINGS'] = 'Настройка параметров договоров, счетов, предложений';

