<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings['LBL_COLOUR_SETTINGS'] = 'Настройка темы';
$mod_strings['LBL_COLOUR_DESC'] = 'Настройка цветовой схемы и параметров темы';
$mod_strings['LBL_COLOUR_ADMIN_INTRO'] = 'Настройка цветовой схемы и параметров темы.'.' <strong>Обратите внимание:</strong> Для отображения сохранённых изменений рекомендуется обновить страницу сочетанием клавиш Ctrl + F5.';

$mod_strings['LBL_DISPLAY_SIDEBAR'] = 'Отображать боковое меню';


$mod_strings['LBL_COLOUR_ADMIN_MENU'] = 'Настройка цветовой схемы меню';
$mod_strings['LBL_COLOUR_ADMIN_PAGE'] = 'Настройка цветовой схемы страниц';
$mod_strings['LBL_COLOUR_ADMIN_PAGEHEADER'] = 'Цвет заголовков на странице';
$mod_strings['LBL_COLOUR_ADMIN_PAGELINK'] = 'Цвет гиперссылок на странице';
$mod_strings['LBL_COLOUR_ADMIN_DASHLET'] = 'Настройка цветовой схемы дашлетов';
$mod_strings['LBL_COLOUR_ADMIN_BUTTON'] = 'Настройка цветовой схемы кнопок';

$mod_strings['LBL_COLOUR_ADMIN_BASE'] = 'Цвет главного меню: ';
$mod_strings['LBL_COLOUR_ADMIN_MENUTOP'] = 'Градиент, верхний цвет меню: ';
$mod_strings['LBL_COLOUR_ADMIN_MENUBOTTOM'] = 'Градиент, нижний цвет меню: ';
$mod_strings['LBL_COLOUR_ADMIN_MENUBRD'] = 'Цвет границы меню: ';
$mod_strings['LBL_COLOUR_ADMIN_MENUHOVER'] = 'Цвет главного меню при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_DDLINK'] = 'Цвет надписей выпадающего меню: ';
$mod_strings['LBL_COLOUR_ADMIN_DDMENU'] = 'Цвет фона выпадающего меню: ';

$mod_strings['LBL_COLOUR_ADMIN_MENUFONT'] = 'Цвет надписи закладок';
$mod_strings['LBL_COLOUR_ADMIN_MENULNKHVR'] = 'Цвет надписи закладок при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNTOP'] = 'Цвет кнопки: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNHOVER'] = 'Цвет кнопки при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNLNK'] = 'Цвет надписи кнопки: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNLNKHOVER'] = 'Цвет надписи кнопки при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_DASHHEAD'] = 'Цвет заголовка дашлета: ';
$mod_strings['LBL_COLOUR_ADMIN_DASHHEAD'] = 'Цвет заголовка дашлета: ';
$mod_strings['LBL_COLOUR_ADMIN_ICON'] = 'Цвет иконок в заголовке дашлета: ';

$mod_strings['LBL_COLOUR_ADMIN_TABS'] = 'Настройка закладок модулей';
