<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings['LBL_SALESAGILITY_ADMIN'] = 'OpenAdmin';
$mod_strings['LBL_AOP_ADMIN_MANAGE_AOP'] = 'Настройки портала';
$mod_strings['LBL_AOP_ENABLE_PORTAL'] = 'Включить портал';
$mod_strings['LBL_AOP_JOOMLA_SETTINGS'] = 'Настройки портала';
$mod_strings['LBL_AOP_JOOMLA_URL'] = 'Joomla URL';
$mod_strings['LBL_AOP_JOOMLA_ACCESS_KEY'] = 'Ключ доступа к Joomla';
$mod_strings['LBL_AOP_CASE_ASSIGNMENT'] = 'Распределение обращений';
$mod_strings['LBL_AOP_DISTRIBUTION_METHOD'] = 'Метод распределения';
$mod_strings['LBL_AOP_ASSIGNMENT_USER'] = 'Пользователь';

$mod_strings['LBL_AOP_EMAIL_SETTINGS'] = 'Настройка шаблонов E-mail для обращений';
$mod_strings['LBL_AOP_CONTACT_EMAIL_TEMPLATE'] = 'Шаблон письма при ответе контактам';
$mod_strings['LBL_AOP_USER_EMAIL_TEMPLATE'] = 'Шаблон письма при ответе пользователям';
$mod_strings['LBL_AOP_CASE_CREATION_EMAIL_TEMPLATE'] = 'Шаблон письма при создании обращения';
$mod_strings['LBL_AOP_CASE_CLOSURE_EMAIL_TEMPLATE'] = 'Шаблон письма при создании обращения';
$mod_strings['LBL_AOP_CASE_REMINDER_EMAIL_TEMPLATE'] = 'Шаблон письма для напоминаний';
$mod_strings['LBL_AOP_JOOMLA_ACCOUNT_CREATION_EMAIL_TEMPLATE'] = 'Шаблон письма при создании учётной записи Joomla';

$mod_strings['LBL_AOP_BUSINESS_HOURS_SETTINGS'] = 'Business Hours';
$mod_strings['LBL_AOP_OPENING_DAYS'] = 'Opening Days';
$mod_strings['LBL_AOP_OPENING_HOURS'] = 'Opening Hours';
$mod_strings['LBL_AOP_CLOSING_HOURS'] = 'Closing Hours';
$mod_strings['LBL_SUPPORT_FROM_ADDRESS'] = 'В качестве адреса отправителя указывать';
$mod_strings['LBL_SUPPORT_FROM_NAME'] = 'В качестве имени отправителя указывать';
$mod_strings['LBL_CREATE_EMAIL_TEMPLATE']  = 'Создать';
$mod_strings['LBL_EDIT_EMAIL_TEMPLATE']  = 'Изменить';
$mod_strings['LBL_SINGLE_USER']  = 'Указанный пользователь';
$mod_strings['LBL_AOP_SETTINGS'] = 'Настройка портала';
$mod_strings['LBL_AOP_DESC'] = 'Настройка параметров портала';
