<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = [

 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Название',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
 'LBL_LIST_FORM_TITLE' => 'Внешние провайдеры OAuth',
 'LBL_MODULE_NAME' => 'Внешние провайдеры OAuth',
 'LBL_MODULE_TITLE' => 'Внешние провайдеры OAuth',
 'LBL_HOMEPAGE_TITLE' => 'Мои внешние провайдеры OAuth',
 'LNK_NEW_RECORD' => 'Создать внешнего провайдера OAuth',

 'LNK_LIST' => 'Внешние провайдеры OAuth',
 'LBL_SEARCH_FORM_TITLE' => 'Поиск внешних провайдеров OAuth',
 'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
 'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
 'LBL_NEW_FORM_TITLE' => 'Новый внешний провайдер OAuth',

 'LBL_LIST_DELETE' => 'Удалить',
 'LBL_TYPE' => 'Тип провайдера',
 'LBL_CONNECTOR' => 'Подключение',
 'LBL_REDIRECT_URI' => 'URI перенаправления',

 'LBL_CLIENT_ID' => 'ID клиента',
 'LBL_CLIENT_SECRET' => 'Секрет клиента',
 'LBL_SCOPE' => 'Область',
 'LBL_URL_AUTHORIZE' => 'URI сервера авторизации',
 'LBL_AUTHORIZE_URL_OPTIONS' => 'Параметры авторизации',
 'LBL_URL_ACCESS_TOKEN' => 'URI токена доступа',
 'LBL_EXTRA_PROVIDER_PARAMS' => 'Дополнительные параметры провайдера',
 'LBL_GET_TOKEN_REQUEST_GRANT' => 'Разрешение при получении токена',
 'LBL_GET_TOKEN_REQUEST_OPTIONS' => 'Параметры запроса  для получения токена',
 'LBL_REFRESH_TOKEN_REQUEST_GRANT' => 'Разрешение при обновлении токена',
 'LBL_REFRESH_TOKEN_REQUEST_OPTIONS' => 'Параметры запроса  для обновления токена',

 'LBL_ACCESS_TOKEN_MAPPING' => 'Сопоставление токена доступа',
 'LBL_EXPIRES_IN_MAPPING' => 'Сопоставление срока действия',
 'LBL_REFRESH_TOKEN_MAPPING' => 'Сопоставление токена обновления',
 'LBL_TOKEN_TYPE_MAPPING' => 'Сопоставление типа токена',

 'LBL_EXTRA' => 'Дополнительные настройки',
 'LBL_MAPPING' => 'Настройки сопоставления',
 'LBL_OTHER' => 'Разное',


 'LNK_LIST_CREATE_NEW_PERSONAL' => 'Создать персонального провайдера OAuth',
 'LNK_LIST_CREATE_NEW_GROUP' => 'Создать группового провайдера OAuth',
 'LNK_LIST_INBOUND_EMAILS' => 'Учётные записи входящей почты',
 'LNK_LIST_OUTBOUND_EMAILS' => 'Учётные записи исходящей почты',
 'LNK_LIST_EXTERNAL_OAUTH_CONNECTION' => 'Внешние подключения OAuth',

 'LBL_OWNER' => 'Владелец',
];
