<?php
/*********************************************************************************
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 
 ********************************************************************************/
  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite  ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the SuiteCRM application.
  *********************************************************************************/

  $mod_strings = array (
$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Событие',
  'LBL_CREATED_USER' => 'Кем создано',
  'LBL_MODIFIED_USER' => 'Изменено пользователем',
  'LBL_LIST_NAME' => 'Событие',
  'LBL_EDIT_BUTTON' => 'Править',
  'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'События',
  'LBL_MODULE_NAME' => 'Событие',
  'LBL_MODULE_TITLE' => 'Событие',
  'LBL_HOMEPAGE_TITLE' => 'Мои события',
  'LNK_NEW_RECORD' => 'Создать событие',
  'LNK_LIST' => 'События',
  'LNK_IMPORT_FP_EVENTS' => 'Импорт событий',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск событий',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_FP_EVENTS_SUBPANEL_TITLE' => 'Событие',
  'LBL_NEW_FORM_TITLE' => 'Новое событие',
  'LBL_LOCATION' => 'Место',
  'LBL_START_DATE' => 'дата начала',
  'LBL_END_DATE' => 'Дата и время окончания',
  'LBL_BUDGET' => 'Бюджет',
  'LBL_FP_EVENTS_FP_EXPENSES_1_FROM_FP_EXPENSES_TITLE' => 'Расходы', ///
  'LBL_INVITE_PDF' => 'Отправить приглашения (PDF)',
  'LBL_INVITE_EMAIL' => 'Отправить приглашения (E-mail)',
  'LBL_PDF_TEMPLATE' => 'Шаблон приглашения (PDF)',
  'LBL_EMAIL_TEMPLATE' => 'Шаблон приглашения (E-mail)',
  'LBL_EDITVIEW_PANEL1' => 'Детали события', 
  'LBL_DEFAULT_SUBPANEL_TITLE' => 'Участники',
);
