<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$app_list_strings = array (
strtolower($object_name).'_category_dom' =>
array (
'' => '',
'Marketing' => 'Маркетинг' ,
'Knowledege Base' => 'База знаний' ,
'Sales' => 'Продажи'    ,
),

strtolower($object_name).'_subcategory_dom' =>
array (
'' => '',
'Marketing Collateral' => 'Маркетинг' ,
'Product Brochures' => 'Брошюры товаров' ,
'FAQ' => 'ЧаВо' ,
),

strtolower($object_name).'_status_dom' =>
array (
'Active' => 'Активен' ,
'Draft' => 'Черновик',
'FAQ' => 'ЧаВо' ,
'Expired' => 'Просрочен' ,
'Under Review' => 'Рассматривается' ,
'Pending' => 'Ожидание решения' ,
),
);
?>
