<?php
/*********************************************************************************
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 
 ********************************************************************************/
  /*********************************************************************************
  *
  * File generated by the RAPIRA Translation Suite  ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/

$mod_strings = array(
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_SECURITYGROUPS' => 'Группы пользователей',
  'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => 'Группы пользователей',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Modified By Id', ///
  'LBL_MODIFIED_NAME' => 'Изменено',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Created By Id', ///
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_SORT_ORDER' => 'Сортировка',
  'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Название',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_NAME' => 'Название',
  'LBL_EDIT_BUTTON' => 'Править',
  'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Параметры вопросов',
  'LBL_MODULE_NAME' => 'Параметры вопросов',
  'LBL_MODULE_TITLE' => 'Параметры вопросов',
  'LBL_HOMEPAGE_TITLE' => 'Мои параметры вопросов',
  'LNK_NEW_RECORD' => 'Создать параметры вопросов',
  'LNK_LIST' => 'Параметры вопросов',
  'LNK_IMPORT_SURVEYQUESTIONOPTIONS' => 'Импорт параметров вопросов',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск параметров вопросов',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_SURVEYQUESTIONOPTIONS_SUBPANEL_TITLE' => 'Параметры вопроса',
  'LBL_NEW_FORM_TITLE' => 'Создать параметры вопросов',
  'LBL_SURVEYQUESTIONOPTIONS_SURVEYQUESTIONRESPONSES_FROM_SURVEYQUESTIONRESPONSES_TITLE' => 'Результаты опроса',
);