<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
 'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
 'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
 'LBL_ID' => 'ID',
 'LBL_DATE_ENTERED' => 'Дата создания',
 'LBL_DATE_MODIFIED' => 'Дата изменения',
 'LBL_MODIFIED' => 'Изменено',
 'LBL_MODIFIED_ID' => 'Изменено(ID)',
 'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
 'LBL_CREATED' => 'Создано',
 'LBL_CREATED_ID' => 'Создано(ID)',
 'LBL_DESCRIPTION' => 'Описание',
 'LBL_DELETED' => 'Удалено',
 'LBL_NAME' => 'Название',
 'LBL_CREATED_USER' => 'Создано',
 'LBL_MODIFIED_USER' => 'Изменено',
 'LBL_LIST_NAME' => 'Имя',
 'LBL_EDIT_BUTTON' => 'Править',
 'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'Индексы',
  'LBL_MODULE_NAME' => 'Индекс',
  'LBL_MODULE_TITLE' => 'Индекс',
  'LBL_HOMEPAGE_TITLE' => 'Мои индексы',
  'LNK_NEW_RECORD' => 'Создать индекс',
  'LNK_LIST' => 'Индексы',
  'LNK_IMPORT_AOD_INDEX' => 'Импорт индексов',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск индексов',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AOD_INDEX_SUBPANEL_TITLE' => 'Индекс',
  'LBL_NEW_FORM_TITLE' => 'Новый индекс',

  'LBL_LOCATION' => 'Расположение',
  'LBL_SEARCH_DOCUMENTS' => 'Поиск документов',
  'LBL_SEARCH_BUTTON' => 'Поиск',
  'LBL_SEARCH_QUERY_PLACEHOLDER' => 'Ведите искомую фразу',
  'LBL_INDEX_STATS' => 'Статистика индексирования',
  'LBL_SEARCH_LABEL' => 'Term', ///
  'LBL_OPTIMISE_NOW' => 'Оптимизировать',
  'LBL_TOTAL_RECORDS' => 'Всего записей:',
  'LBL_INDEXED_RECORDS' => 'Всего проиндексировано записей:',
  'LBL_UNINDEXED_RECORDS' => 'Непроиндексированных записей:',
  'LBL_FAILED_RECORDS' => 'Не удалось проиндексировать:',
  'LBL_LAST_OPTIMISED' => 'Время последней оптимизации:', 
  'LBL_INDEX_FILES' => 'Индексных файлов:', 
  'LBL_SEARCH_RESULT_SCORE' => 'Соответствие запросу(%)',
  'LBL_SEARCH_RESULT_MODULE' => 'Модуль',
  'LBL_SEARCH_RESULT_NAME' => 'Запись',
  'LBL_SEARCH_RESULT_DATE_CREATED' => 'Дата создания',
  'LBL_SEARCH_RESULT_DATE_MODIFIED' => 'Дата изменения',
  'LBL_SEARCH_RESULT_EMPTY' => 'Ничего не обнаружено',
  'LBL_SEARCH_RESULT_SUMMARY' => 'Краткая информация',
  'LBL_FAILED_INDEX_MODULE' => 'Модуль',
  'LBL_FAILED_INDEX_NAME' => 'Запись',
  'LBL_FAILED_INDEX_DATE' => 'Дата',
  'LBL_FAILED_INDEX_ERROR' => 'Ошибка',
  'LBL_NEVER_OPTIMISED' => 'Не оптимизировано',
  'LBL_USE_AOD_SEARCH' => 'Использовать полнотекстовый поиск',
  'LBL_USE_VANILLA_SEARCH' => 'Использовать стандартный поиск',
);