<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$object_name = strtolower($object_name);
$app_list_strings = array (

$object_name.'_type_dom' =>
array (
'Administration' => 'Ведение',
'Product' => 'Результат',
'User' => 'Клиентское',
),
$object_name.'_status_dom' =>
array (
'New' => 'Новое' ,
'Assigned' => 'Назначенное' ,
'Closed' => 'Закрытое' ,
'Pending Input' => 'Ожидание решения' ,
'Rejected' => 'Отклонённое'    ,
'Duplicate' => 'Дублировать' ,
),
$object_name.'_priority_dom' =>
array (
'P1' => 'Высокий' ,
'P2' => 'Средний' ,
'P3' => 'Низкий'    ,
),
$object_name.'_resolution_dom' =>
array (
'' => '' ,
'Accepted' => 'Принято' ,
'Duplicate' => 'Дублировать' ,
'Closed' => 'Закрытое' ,
'Out of Date' => 'Устарело' ,
'Invalid' => 'Недействительно' ,
),
);
?>
