<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array_merge($mod_strings,
    array(
        'LBL_SUITE_SUPERCHARGED' => "Supercharged by SuiteCRM",
        'LBL_SUITE_POWERED_BY' => "Powered By SugarCRM",
        'LBL_SUITE_TOP' => "Назад",
        'LBL_SUITE_PRINT' => "Печать",
        'LBL_SUITE_DESC1' => 'SuiteCRM has been written and assembled by SalesAgility, one of the worlds most knowledgeable SugarCRM consultancies.',
        'LBL_SUITE_DESC2' => 'SuiteCRM is intended to deliver on the promise of SugarCRM - a freely available open source CRM project that combines great functionality, with community and commitment.',
        'LBL_SUITE_DESC3' => 'There will be no licenced software as part of the project managed by SalesAgility. All the code is free. All the code is available for free download. There is no hidden agenda to charge for access to the code. It is and always will be free and open source. There will be no paid-for versions.',
        'LBL_QUICK_ACCOUNT' => 'Создать контрагента',
        'LBL_QUICK_CONTACT' => 'Создать контакт',
        'LBL_QUICK_OPPORTUNITY' => 'Create Opportunity',
        'LBL_QUICK_LEAD' => 'Создать предварит. контакт',
        'LBL_QUICK_DOCUMENT' => 'Создать документ',
        'LBL_QUICK_CALL' => 'Назначить звонок',
        'LBL_QUICK_TASK' => 'Создать задачу',
    )
);
?>

