<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_MODULE_NAME' => 'Версии' ,
'LBL_MODULE_TITLE' => 'Версии - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск версий' ,
'LBL_LIST_FORM_TITLE' => 'Список версий' ,
'LBL_NEW_FORM_TITLE' => 'Новая версия' ,
'LBL_RELEASE' => 'Версия:' ,
'LBL_LIST_NAME' => 'Версия' ,
'LBL_NAME' => 'Версия:' ,
'LBL_LIST_LIST_ORDER' => 'Порядок' ,
'LBL_LIST_ORDER' => 'Порядок:' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_STATUS' => 'Статус:' ,
'LNK_NEW_RELEASE' => 'Список версий' ,
'NTC_DELETE_CONFIRMATION' => 'Вы уверены, что хотите удалить эту запись?' ,
'ERR_DELETE_RECORD' => 'Вы должны указать запись для удаления версии.' ,
'NTC_STATUS' => 'Установите статус на "Не активна" для удаления этой версии из списка' ,
'NTC_LIST_ORDER' => 'Установить порядок следования версий' ,
'release_status_dom' =>
array (
'Active' => 'Активна' ,
'Inactive' => 'Не активна'   ,
),
'LBL_EDITLAYOUT' => 'Изменить макет' /*for 508 compliance fix*/,
);


?>
