<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$connector_strings = array (
    'LBL_GET_STARTED' => 'Get Started!',
    'LBL_TOS0' => 'I agree to InsideView\'s  ',
    'LBL_TOS1' => 'Terms of Use',
    'LBL_TOS3' => 'Privacy Policy',
    'iv_description0' => 'By clicking "Get Started" you agree to InsideView\'s',
    'LBL_OPP' => 'Find Opportunities',
    'LBL_OPP_SUB' => 'to reach out to customers',
    'LBL_REFERRAL' => 'Get Referrals',
    'LBL_REFERRAL_SUB' => 'to key decision makers',
    'LBL_ENGAGE' => 'Engage Customers',
    'LBL_ENGAGE_SUB' => 'with conversation starters',
);

?>