<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_BLANK'=> ' ',

'LBL_MODULE_NAME' => 'Звонки' ,
'LBL_MODULE_TITLE' => 'Звонки - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск звонка' ,
'LBL_LIST_FORM_TITLE' => 'Список звонков' ,
'LBL_NEW_FORM_TITLE' => 'Назначить мероприятие' ,
'LBL_LIST_CLOSE' => 'Закрыть' ,
'LBL_LIST_SUBJECT' => 'Тема' ,
'LBL_LIST_CONTACT' => 'Контакт' ,
'LBL_LIST_RELATED_TO' => 'Относится к' ,
'LBL_LIST_RELATED_TO_ID' => 'Относится к ID',
'LBL_LIST_DATE' => 'Дата звонка' ,
'LBL_LIST_TIME' => 'Время' , ////
'LBL_LIST_DURATION' => 'Продолжительность' ,
'LBL_LIST_DIRECTION' => 'Направление' ,
'LBL_SUBJECT' => 'Тема звонка:' ,
'LBL_REMINDER' => 'Напоминание:' ,
'LBL_CONTACT_NAME' => 'Контакт:' ,
'LBL_DESCRIPTION_INFORMATION' => 'Описание' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_DIRECTION' => 'Направление:' ,
'LBL_DATE' => 'Дата звонка:' ,
'LBL_DURATION' => 'Продолжительность:' ,
'LBL_DURATION_HOURS' => 'Продолжительность (час.):' ,
'LBL_DURATION_MINUTES' => 'Продолжительность (мин.):' ,
'LBL_HOURS_MINUTES' => '(часов:минут)' ,
'LBL_CALL' => 'Звонок:' ,
'LBL_DATE_TIME' => 'Дата и время:' ,
'LBL_TIME' => 'Время:' ,
'LBL_HOURS_ABBREV' => 'час.' ,
'LBL_MINSS_ABBREV' => 'мин.' ,
'LBL_COLON' => ':' , ///
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_CALL_LIST' => 'Звонки' ,
'LNK_IMPORT_CALLS' => 'Импорт звонков',
'ERR_DELETE_RECORD' => 'Перед удалением должен быть указан номер записи.' ,
'NTC_REMOVE_INVITEE' => 'Вы уверены, что хотите удалить это приглашённое лицо из данного звонка?' ,
'LBL_INVITEE' => 'Приглашённые' ,
'LBL_RELATED_TO' => 'Относится к:' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,
'LBL_SCHEDULING_FORM_TITLE' => 'Планирование' ,
'LBL_ADD_INVITEE' => 'Добавить приглашённых' ,
'LBL_NAME' => 'Имя' ,
'LBL_FIRST_NAME' => 'Имя' ,
'LBL_LAST_NAME' => 'Фамилия' ,
'LBL_EMAIL' => 'E-mail' ,
'LBL_PHONE' => 'Тел.' ,

'LBL_REMINDER_POPUP' => 'Во всплывающем окне',
'LBL_REMINDER_EMAIL' => 'E-mail',
'LBL_REMINDER_EMAIL_ALL_INVITEES' => 'Отправить E-mail приглашённым',
'LBL_EMAIL_REMINDER' => 'Напоминание при помощи E-mail',
'LBL_EMAIL_REMINDER_TIME' => 'Время напоминания по E-mail',
'LBL_SEND_BUTTON_TITLE'=> 'Сохранить и отправить приглашения' ,
'LBL_SEND_BUTTON_KEY'=> 'I' , ///
'LBL_SEND_BUTTON_LABEL'=> 'Сохранить и отправить приглашения' ,
'LBL_DATE_END'=> 'Дата окончания' ,
'LBL_TIME_END'=> 'Время окончания' ,
'LBL_REMINDER_TIME'=> 'Время напоминания' ,
'LBL_EMAIL_REMINDER_SENT' => 'Напоминание по E-mail отправлено',
'LBL_SEARCH_BUTTON'=> 'Найти' ,
'LBL_ACTIVITIES_REPORTS' => 'Отчёты по мероприятиям', ///
'LBL_ADD_BUTTON'=> 'Добавить' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Звонки' ,
'LBL_LOG_CALL'=> 'Журнал звонков' ,
'LNK_SELECT_ACCOUNT'=> 'Выбор контрагента' ,
'LNK_NEW_ACCOUNT'=> 'Новый контрагент' ,
'LNK_NEW_OPPORTUNITY'=> 'Новая сделка' ,
'LBL_DEL' => 'Удалить' ,
'LBL_LEADS_SUBPANEL_TITLE' => 'Предварительные контакты',
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_USERS_SUBPANEL_TITLE' => 'Пользователи' ,
'LBL_OUTLOOK_ID' => 'ID Outlook' ,
'LBL_MEMBER_OF' => 'Состоит в' ,
'LBL_HISTORY_SUBPANEL_TITLE' => 'Заметки'  ,
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_LIST_MY_CALLS' => 'Мои звонки',
'LBL_SELECT_FROM_DROPDOWN' => 'Прежде всего выберите значение из списка "Относится к".',
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
'NOTICE_DURATION_TIME' => 'Продолжительность разговора должна быть больше 0 минут',
'LBL_CALL_INFORMATION' => 'Основная информация',
'LBL_REMOVE' => 'удал.',
'LBL_ACCEPT_STATUS' => 'Статус приглашения',
'LBL_ACCEPT_LINK' => 'Accept Link', ///
//For export labels  ///
'LBL_PARENT_ID' => 'ID родителя',
'LBL_EXPORT_MODIFIED_USER_ID' => 'Изменено(ID)', ////
'LBL_EXPORT_CREATED_BY' => 'Создано (ID)', ////
'LBL_EXPORT_ASSIGNED_USER_ID' => 'Ответственный(ая)-ID', ////
'LBL_EXPORT_DATE_START' => 'Дата и время начала', ////
'LBL_EXPORT_PARENT_TYPE' => 'Относится к модулю', ////
'LBL_EXPORT_REMINDER_TIME' => 'Напоминание (минуты)', ////

// create invitee functionallity
'LBL_CREATE_INVITEE' => 'Составить приглашение:',
'LBL_CREATE_CONTACT' => 'Создав новый контакт',
'LBL_CREATE_LEAD' => 'Создав новый предварит. контакт',
'LBL_CREATE_AND_ADD' => 'Создать',
'LBL_CANCEL_CREATE_INVITEE' => 'Отказаться',
'LBL_EMPTY_SEARCH_RESULT' => 'По указанным критериям ничего не обнаружено. Вы можете создать приглашение "с нуля", добавив в него новые контакты / предварительные контакты.',
'LBL_NO_ACCESS' => 'У вас нет прав на создание записи в модуле $module',

'LBL_REPEAT_TYPE' => 'Тип повтора',
'LBL_REPEAT_INTERVAL' => 'Интервал повтора',
'LBL_REPEAT_DOW' => 'Repeat Dow',
'LBL_REPEAT_UNTIL' => 'Прекратить',
'LBL_REPEAT_COUNT' => 'Число повторов',
'LBL_REPEAT_PARENT_ID' => 'ID родителя',
'LBL_RECURRING_SOURCE' => 'Источник повтора',
'LBL_SYNCED_RECURRING_MSG' => 'Данные о звонке были созданы в другой программе и синхронизированы с SuiteCRM. Для изменения данной записи откройте первоначальную программу, внесите в соответствующий звонок необходимые изменения и вновь синхронизируйте данные с SuiteCRM.',

    // for reminders
    'LBL_REMINDERS' => 'Напоминания',
    'LBL_REMINDERS_ACTIONS' => 'Напомнить о мероприятии в виде:',
    'LBL_REMINDERS_POPUP' => 'Всплывающего уведомления браузера',
    'LBL_REMINDERS_EMAIL' => 'Приглашения по E-mail',
    'LBL_REMINDERS_WHEN' => 'Когда:',
    'LBL_REMINDERS_REMOVE_REMINDER' => 'Удалить напоминание',
    'LBL_REMINDERS_ADD_ALL_INVITEES' => 'Добавить ВСЕХ приглашённых',
    'LBL_REMINDERS_ADD_REMINDER' => 'Добавить напоминание',
	
	'LBL_RESCHEDULE' => 'Отложить звонок',
    'LBL_RESCHEDULE_COUNT' => 'Попыток дозвона',
    'LBL_RESCHEDULE_DATE' => 'Дата',
    'LBL_RESCHEDULE_REASON' => 'Причина',
    'LBL_RESCHEDULE_ERROR1' => 'Укажите правильную дату',
    'LBL_RESCHEDULE_ERROR2' => 'Укажите причину, по которой звонок отложен',
    'LBL_RESCHEDULE_PANEL' => 'Отложенные звонки',
    'LBL_RESCHEDULE_HISTORY' => 'История дозвона',
	'LBL_CANCEL' => 'Отказаться',
    'LBL_SAVE' => 'Сохранить',
	
);


?>
