<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_SALUTATION'=> 'Приветствие' ,
'LBL_NAME'=> 'Имя:' ,
'LBL_FIRST_NAME'=> 'Имя:' ,
'LBL_LAST_NAME'=> 'Фамилия:' ,
'LBL_TITLE'=> 'Должность:' ,
'LBL_DEPARTMENT'=> 'Отдел:' ,
'LBL_DO_NOT_CALL'=> 'Не звонить:' ,
'LBL_HOME_PHONE'=> 'Тел. (дом.):' ,
'LBL_MOBILE_PHONE'=> 'Тел. (моб.):' ,
'LBL_OFFICE_PHONE'=> 'Тел. (раб.):' ,
'LBL_OTHER_PHONE'=> 'Другой тел.:' ,
'LBL_FAX_PHONE'=> 'Факс:' ,
'LBL_EMAIL_ADDRESS'=> 'E-mail:' ,
'LBL_PRIMARY_ADDRESS'=> 'Основной адрес:' ,
'LBL_PRIMARY_ADDRESS_STREET'=> 'Основной адрес - улица:' ,
'LBL_PRIMARY_ADDRESS_STREET_2' => 'Основной адрес - улица 2:',
'LBL_PRIMARY_ADDRESS_STREET_3' => 'Основной адрес - улица 3:',
'LBL_PRIMARY_ADDRESS_CITY'=> 'Основной адрес - город:' ,
'LBL_PRIMARY_ADDRESS_STATE'=> 'Основной адрес - область:' ,
'LBL_PRIMARY_ADDRESS_POSTALCODE'=> 'Основной адрес - индекс:' ,
'LBL_PRIMARY_ADDRESS_COUNTRY' => 'Основной адрес - страна:' ,
'LBL_ALT_ADDRESS'=> 'Другой адрес',
'LBL_ALT_ADDRESS_STREET'=> 'Другой адрес - улица:' ,
'LBL_ALT_ADDRESS_STREET_2' => 'Другой адрес - улица 2:',
'LBL_ALT_ADDRESS_STREET_3' => 'Другой адрес - улица 3:',
'LBL_ALT_ADDRESS_CITY'=> 'Другой адрес - город:' ,
'LBL_ALT_ADDRESS_STATE'=> 'Другой адрес - область:' ,
'LBL_ALT_ADDRESS_POSTALCODE'=> 'Другой адрес - индекс:' ,
'LBL_ALT_ADDRESS_COUNTRY'=> 'Другой адрес - страна:' ,

'LBL_STREET'=> 'Другой адрес',
'LBL_PRIMARY_STREET'=>'Адрес',
'LBL_ALT_STREET'=>'Другой адрес',
'LBL_CITY'=> 'Город:' ,
'LBL_STATE'=> 'Область:' ,
'LBL_POSTALCODE'=> 'Индекс',
'LBL_POSTAL_CODE'=> 'Индекс:' ,
'LBL_COUNTRY'=> 'Страна:' ,
'LBL_CONTACT_INFORMATION'=> 'Контактная информация' ,
'LBL_ADDRESS_INFORMATION'=> 'Адресная информация' ,

'LBL_ASSIGNED_TO_NAME'=> 'Пользователь: ' ,
'LBL_OTHER_EMAIL_ADDRESS' => 'Дополнительный E-mail:',
'LBL_ASSISTANT'=> 'Помощник:' ,
'LBL_ASSISTANT_PHONE'=> 'Помощник - тел.:' ,
'LBL_WORK_PHONE'=> 'Тел. (раб.)',
'LNK_IMPORT_VCARD' => 'Создать из vCard',
'LBL_ANY_EMAIL' => 'Любой E-mail',
'LBL_EMAIL_NON_PRIMARY' => 'Доп. E-mail',
'LBL_PHOTO' => 'Фото',

'LBL_EDIT_BUTTON' => 'Править',
'LBL_REMOVE' => 'Удалить',
);
