<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_REPLY_ADDR' => 'Ответить (адрес): ',
'LBL_REPLY_NAME' => 'Ответить (имя): ',

'LBL_MODULE_NAME' => 'Рассылки E-mail' ,
'LBL_MODULE_TITLE' => 'Рассылки E-mail: ГЛАВНАЯ' ,
'LBL_LIST_FORM_TITLE' => 'Рассылки E-mail' ,
'LBL_NAME' => 'Название: ' ,
'LBL_LIST_NAME' => 'Название' ,
'LBL_LIST_FROM_ADDR' => 'От' ,
'LBL_LIST_DATE_START' => 'Дата начала' ,
'LBL_LIST_TEMPLATE_NAME' => 'Шаблон E-mail' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_STATUS' => 'Статус' ,
'LBL_QUEUEING_STATUS' => 'Статус размещения в очереди',
'LBL_STATUS_TEXT' => 'Статус:' ,
'LBL_TEMPLATE_NAME' => 'Название шаблона',
'LBL_DATE_ENTERED' => 'Дата ввода' ,
'LBL_DATE_MODIFIED' => 'Дата изменения' ,
'LBL_MODIFIED' => 'Исправлено: ' ,
'LBL_CREATED' => 'Создано: ' ,
'LBL_MESSAGE_FOR' => 'Отправить это сообщение:' ,

'LBL_FROM_NAME' => 'От - имя: ' ,
'LBL_FROM_ADDR' => 'От - адрес E-mail: ' ,
'LBL_DATE_START' => 'Дата начала' ,
'LBL_SEND_DATE' => 'Дата отправки',///
'LBL_SCHEDULED_START_DATE' => 'Запланированная дата рассылки',
'LBL_CHECK_DUPLICATE' => 'Обработка дубликатов',
'LBL_TIME_START' => 'Время начала' ,
'LBL_START_DATE_TIME' => 'Дата и время начала: ' ,
'LBL_TEMPLATE' => 'Шаблон E-mail: ' ,
'LBL_TEMPLATE_SELECTED' => 'Шаблон',

'LBL_MODIFIED_BY' => 'Кем исправлено: ' ,
'LBL_CREATED_BY' => 'Кем создано: ' ,

'LNK_NEW_CAMPAIGN' => 'Создать маркет. кампанию' ,
'LNK_CAMPAIGN_LIST' => 'Маркетинговые кампании' ,
'LBL_RELATED_CAMPAIGN' => 'Маркетинговая кампания',
'LNK_NEW_PROSPECT_LIST' => 'Создать список адресатов' ,
'LNK_PROSPECT_LIST_LIST' => 'Списки адресатов' ,
'LNK_NEW_PROSPECT' => 'Создать адресата' ,
'LNK_PROSPECT_LIST' => 'Адресаты' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Рассылки E-mail' ,
'LBL_CREATE_EMAIL_TEMPLATE' => 'Создать' ,
'LBL_EDIT_EMAIL_TEMPLATE' => 'Править' ,
'LBL_FROM_MAILBOX' => 'Почтовый ящик для возвращаемых писем' ,
'LBL_FROM_MAILBOX_NAME' => 'Почтовый ящик для возвращаемых писем:' ,
'LBL_OUTBOUND_EMAIL_ACCOUNT_NAME' => 'Учётная запись для исходящей почты:',
'LBL_FROM' => 'От',
'LBL_PROSPECT_LIST_SUBPANEL_TITLE' => 'Адресаты' ,
'LBL_ALL_PROSPECT_LISTS' => 'ВСЕМ спискам адресатов маркетинговой кампании' ,
'LBL_RELATED_PROSPECT_LISTS' => 'ВЫБРАННЫМ спискам адресатов маркетинговой кампании.' ,
'LBL_PROSPECT_LIST_NAME' => 'Имя:' ,
'LBL_TARGET_LISTS' => 'Списки Адресатов',

'LBL_LIST_PROSPECT_LIST_NAME'=> 'Список адресатов' ,
'LBL_MODULE_SEND_TEST'=> 'Рассылка: проверка отправки' ,
'LBL_MODULE_SEND_EMAILS'=> 'Рассылка: отправить E-mail' ,
'LBL_SCHEDULE_MESSAGE_TEST'=> 'Пожалуйста, выберите рассылки, которые вы хотите протестировать' ,
'LBL_SCHEDULE_MESSAGE_EMAILS'=> 'Пожалуйста, выберите рассылки, которые вы хотите запланировать к отправке в определённое время:' ,
'LBL_SCHEDULE_BUTTON_TITLE'=> 'Отправить' ,
'LBL_SEND_BUTTON_LABEL' => 'Отправить',
'LBL_SCHEDULE_BUTTON_LABEL'=> 'Запланировать' ,
'LBL_ERROR_ON_MARKETING' => 'Обязательные поля не заполнены',

'LBL_CAMPAIGN_ID' => 'Маркет. кампания (ID)',
'LBL_OUTBOUND_EMAIL_ACOUNT_ID' => 'ID учётной записи исходящей почты',
'LBL_EMAIL_TEMPLATE' => 'Шаблон E-mail',
'LBL_PROSPECT_LISTS' => 'Списки адресатов',
'LBL_OVERVIEW' => 'Настройки',
'LBL_EMAIL_CONFIG' => 'Настройки E-mail',
'LBL_CONFIGS' => 'Настройки рассылки',
'LBL_EMAIL' => 'Содержимое письма',
'LBL_BODY' => 'Сообщение',
'LBL_MARKETING_TYPE' => 'Тип маркетинговой кампании',
'LBL_SURVEY' => 'Опрос',
'LBL_SCHEDULE' => 'Запланировать',
'LBL_DELETE_TEST_ENTRIES' => 'Удалить тестовые данные',
'LBL_UNSCHEDULE' => 'Отменить запланированную рассылку',
'LBL_ABORT' => 'Прервать рассылку',
'LBL_USERS' => 'Пользователи',
'LBL_SEND_TEST_EMAIL' => 'Выполнить тестовую рассылку',
'LBL_SELECT_RECORDS_WITH_EMAILS' => 'Выберите записи, содержащие электронную почту',
'LBL_MESSAGE_QUEUE_TITLE' => 'В очереди',
'LBL_SCHEDULED_START_DATE_HELP' => 'Рассылка осуществляется в пакетном режиме, что занимает некоторое время.',
'LBL_TARGET_LISTS_HELP' => 'Получатели рассылки. Рассылка получателям, находящимся в списках исключений, будет заблокирована.',
'LBL_STATUS_DRAFT_NOT_SEND_HELP' => 'Рассылка начнётся после перевода кампании в статус "Запланирована".',
'LBL_TYPE_MARKETING_HELP' => 'Текст письма должен содержать ссылку для отписки.',
'LBL_TYPE_LEGACY_HELP' => 'Это устаревший тип рассылки, отображается в ознакомительных целях.',
'LBL_TYPE_TRANSACTIONAL_HELP' => 'Текст письма НЕ должен содержать ссылку для отписки.',

'LBL_SCHEDULER_WIDGET' => 'Диагностика маркетинговой кампании',
'LBL_OOTB_SEND_EMAIL_TO_QUEUE' => 'Добавлять рассылку в очередь',
'LBL_OOTB_BOUNCE' => 'Проверять почтовые ящики для возвращаемых писем',
'LBL_OOTB_SEND_EMAIL_FROM_QUEUE' => 'Запускать рассылку',
'LBL_SCHEDULERS' => 'Задания Планировщика',
'LBL_INBOUND_EMAIL' => 'Возвращаемые письма',
'LBL_TRACKERS_ENABLED' => 'Включены ли трекеры?',
'LBL_TRACKER_LINKS_ENABLED' => 'Включены ли трекеры?',
'LBL_TRACKERS_ENABLED_FOOTNOTE' => 'Рассылаемые письма содержат трекеры для учёта активности получателей (просмотры, переходы по ссылкам).',
'LBL_TRACKERS_DISABLED_FOOTNOTE' => 'Рассылаемые письма НЕ содержат трекеры для учёта активности получателей (просмотры, переходы по ссылкам).',
'LBL_TRACKERS_DISABLED_GLOBALLY_FOOTNOTE' => 'Трекеры отключены администратором системы, активность получателей (просмотры, переходы по ссылкам) не будет отслеживаться.',
'LBL_HAS_TEST_DATA' => 'Содержит тестовые данные',
);
