<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$dashletStrings['RSSDashlet'] = array('LBL_TITLE'            => 'Лента новостей',
'LBL_DESCRIPTION'      => 'Лента новостей',
'LBL_SAVING'           => 'Анализ ...',
'LBL_SAVED'            => 'Готово',
'LBL_AUTO_SCROLL'      => 'Автопрокрутка',
'LBL_SCROLL_SPEED'      => 'Скорость автопрокрутки (%)',
'LBL_CONFIGURE_TITLE'  => 'Заголовок',
'LBL_CONFIGURE_HEIGHT' => 'Высота (1 - 300)',
'LBL_CONFIGURE_RSSURL' => 'Url',
'LBL_DBLCLICK_HELP'    => '',
'ERR_LOADING_FEED'     => 'Ошибка загрузки',
);
?>
