<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (

'LBL_NAME' => 'Задание',
'LBL_EXECUTE_TIME'=> 'Время выполнения',
'LBL_SCHEDULER_ID' 	=> 'Планировщик',
'LBL_STATUS' 	=> 'Статус задания',
'LBL_RESOLUTION' 	=> 'Результат',
'LBL_MESSAGE' 	=> 'Сообщения',
'LBL_DATA' 	=> 'Данные',
'LBL_REQUEUE' 	=> 'Повторять при неудаче',
'LBL_RETRY_COUNT' 	=> 'Количество повторов',
'LBL_FAIL_COUNT' 	=> 'Неудачи',
'LBL_INTERVAL' 	=> 'Минимальный интервал между повторами',
'LBL_CLIENT' 	=> 'Owning client',
'LBL_PERCENT'	=> 'Процент выполнения',
// Errors
'ERR_CALL' 	=> 'Ошибка вызова функции: %s',
'ERR_CURL' => 'CURL  не установлен - нет возможности запускать удалённые задания',
'ERR_FAILED' => 'Неизвестная ошибка, проверьте логи PHP и suitecrm.log',
'ERR_PHP' => '%s [%d]: %s в %s в строке %d',
'ERR_NOUSER' => 'Не указан ID пользователя для данного задания',
'ERR_NOSUCHUSER' => 'ID %s не обнаружен',
'ERR_JOBTYPE' 	=> 'Неизвестный тип задания: %s',
'ERR_TIMEOUT' => 'Истёк тайм-аут',
'ERR_JOB_FAILED_VERBOSE' => 'Не удалось выполнить задание %1$s (%2$s), указанное в CRON',
);

?>
