<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA ->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the SuiteCRM application.
  *********************************************************************************/
 // Replaced by RAPIRA <-

/**
 * Module-specific labels for Processes.
 * Shared async task labels are inherited from the asynctask template language file.
 */
$mod_strings = [

    // Module naming
    'LBL_LIST_FORM_TITLE' => 'Процессы',
    'LBL_MODULE_NAME' => 'Процессы',
    'LBL_MODULE_TITLE' => 'Процессы',
    'LBL_HOMEPAGE_TITLE' => 'Мои процессы',
    'LNK_NEW_RECORD' => 'Создать процесс',
    'LNK_LIST' => 'Процессы',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск процессов',
    'LBL_NEW_FORM_TITLE' => 'Новый процесс',

    // Rerun/dismiss confirmation messages (reference this module by name)
    'LBL_RERUN_CONFIRMATION' => 'Вы действительно хотите повторно запустить эту миграцию с нуля? Все существующие элементы, прошедшие миграцию, будут удалены, и миграция будет перезапущена.',
    'LBL_RERUN_SUCCESS' => 'Миграция повторно поставлена ​​в очередь и будет перезапущена сначала.',
	'LBL_DISMISS_CONFIRMATION' => 'Вы действительно хотите закрыть это задание миграции? Будет удалено как само задание, так и все связанные с ней данные.',
	'LBL_DISMISS_SUCCESS' => 'Задание миграции успешно закрыто.',

    // Type footnotes
	'LBL_TYPE_BACKGROUND_HELP' => 'Миграция выполняется в фоновом режиме через обработчик очереди сообщений. Элементы обрабатываются партиями, пользовательский интерфейс в процессе выполнения миграции не блокируется.',
	'LBL_TYPE_IMMEDIATE_HELP' => 'Миграция выполняется немедленно после запуска. Все элементы обрабатываются единым запросом, процесс может занять значительное количество времени при обработке больших объёмов данных.',
];
