<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
    'LBL_ID' => 'ID',
    'LBL_DATE_ENTERED' => 'Дата создания',
    'LBL_DATE_MODIFIED' => 'Дата изменения',
    'LBL_MODIFIED' => 'Изменено',
    'LBL_MODIFIED_ID' => 'Изменено(ID)',
    'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
    'LBL_CREATED' => 'Создано',
    'LBL_CREATED_ID' => 'Создано(ID)',
    'LBL_DESCRIPTION' => 'Описание',
    'LBL_DELETED' => 'Удалено',
    'LBL_NAME' => 'Отчёт',
    'LBL_CREATED_USER' => 'Создано',
    'LBL_MODIFIED_USER' => 'Изменено',
    'LBL_LIST_NAME' => 'Имя',
    'LBL_EDIT_BUTTON' => 'Править',
    'LBL_REMOVE' => 'Удалить',
    'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
    'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_LIST_FORM_TITLE' => 'Отчёты',
  'LBL_MODULE_NAME' => 'Отчёты',
  'LBL_MODULE_TITLE' => 'Отчёты',
  'LBL_HOMEPAGE_TITLE' => 'Мои отчёты',
  'LNK_NEW_RECORD' => 'Создать отчёт',
  'LNK_LIST' => 'Отчёты',
  'LNK_IMPORT_AOR_REPORTS' => 'Импорт отчётов',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск отчётов',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AOR_REPORTS_SUBPANEL_TITLE' => 'Отчёты',
  'LBL_NEW_FORM_TITLE' => 'Новый отчёт',
  'LBL_REPORT_MODULE' => 'Модуль',
  'LBL_GRAPHS_PER_ROW' => 'Диаграмм в строке отчёта',
  'LBL_FIELD_LINES' => 'Поля отчёта',
  'LBL_ADD_FIELD' => 'Добавить поле',
  'LBL_CONDITION_LINES' => 'Условия',
  'LBL_ADD_CONDITION' => 'Добавить условие',
  'LBL_EXPORT' => 'Экспорт',
  'LBL_DOWNLOAD_PDF' => 'Сохранить в PDF',
  'LBL_ADD_TO_PROSPECT_LIST' => 'Добавить в список адресатов',
  'LBL_AOR_MODULETREE_SUBPANEL_TITLE' => 'Модули',
  'LBL_AOR_FIELDS_SUBPANEL_TITLE' => 'Поля',
  'LBL_AOR_CONDITIONS_SUBPANEL_TITLE' => 'Условия',
  'LBL_TOTAL' => 'Итоговая строка',
  'LBL_AOR_CHARTS_SUBPANEL_TITLE' => 'Диаграммы',
  'LBL_ADD_CHART' => 'Добавить диаграмму',
  'LBL_ADD_PARENTHESIS' => 'Добавить скобки',
  'LBL_CHART_TITLE' => 'Название',
  'LBL_CHART_TYPE' => 'Тип',
  'LBL_CHART_X_FIELD' => 'Ось X',
  'LBL_CHART_Y_FIELD' => 'Ось Y',
  'LBL_AOR_REPORTS_DASHLET' => 'Отчёты',
  'LBL_DASHLET_TITLE' => 'Заголовок',
  'LBL_DASHLET_REPORT' => 'Отчёт',
  'LBL_DASHLET_CHOOSE_REPORT' => 'Укажите необходимый отчёт',
  'LBL_DASHLET_SAVE' => 'Сохранить',
  'LBL_DASHLET_CHARTS' => 'Диаграммы',
  'LBL_DASHLET_ONLY_CHARTS' => 'Отображать только диаграммы',
  'LBL_AOR_SCHEDULED_REPORTS_AOR_REPORTS_FROM_AOR_SCHEDULED_REPORTS_TITLE' => 'Отчёты по расписанию',
  'LBL_UPDATE_PARAMETERS' => 'Обновить',
  'LBL_PARAMETERS' => 'Условия',
  'LBL_TOOLTIP_DRAG_DROP_ELEMS' => 'Переместите выбранный элемент в список ', ///
  'LBL_MAIN_GROUPS' => 'Основная группа:',
  'LBL_CHAR_UNNAMED_DEFAULT_TITLE' => 'Без названия ',
  'LBL_REPORT' => 'Отчёт',
);
