<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings['LBL_AOP_CASE_UPDATES'] = 'Обновления обращения';
$mod_strings['LBL_CREATE_PORTAL_USER'] = "Создать пользователя портала";
$mod_strings['LBL_ENABLE_PORTAL_USER'] = "Включить пользователя портала";
$mod_strings['LBL_DISABLE_PORTAL_USER'] = "Отключить пользователя портала";
$mod_strings['LBL_CREATE_PORTAL_USER_FAILED'] = "Ошибка создания пользователя портала";
$mod_strings['LBL_ENABLE_PORTAL_USER_FAILED'] = "Ошибка включения пользователя портала";
$mod_strings['LBL_DISABLE_PORTAL_USER_FAILED'] = "Ошибка отключения пользователя портала";
$mod_strings['LBL_CREATE_PORTAL_USER_SUCCESS'] = "Создать пользователя портала";
$mod_strings['LBL_ENABLE_PORTAL_USER_SUCCESS'] = "Включить пользователя портала";
$mod_strings['LBL_DISABLE_PORTAL_USER_SUCCESS'] = "Отключить пользователя портала";
$mod_strings['LBL_NO_JOOMLA_URL'] = "Не указан URL портала";
$mod_strings['LBL_PORTAL_USER_TYPE'] = "Пользователь портала";
