<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалено',
  'LBL_NAME' => 'Событие',
  'LBL_CREATED_USER' => 'Кем создано',
  'LBL_MODIFIED_USER' => 'Изменено пользователем',
  'LBL_LIST_NAME' => 'Событие',
  'LBL_EDIT_BUTTON' => 'Править',
  'LBL_REMOVE' => 'Удалить',
  'LBL_LIST_FORM_TITLE' => 'События',
  'LBL_MODULE_NAME' => 'Событие',
  'LBL_MODULE_TITLE' => 'Событие',
  'LBL_HOMEPAGE_TITLE' => 'Мои события',
  'LNK_NEW_RECORD' => 'Создать событие',
  'LNK_LIST' => 'События',
  'LNK_IMPORT_FP_EVENTS' => 'Импорт событий',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск событий',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_FP_EVENTS_SUBPANEL_TITLE' => 'Событие',
  'LBL_NEW_FORM_TITLE' => 'Новое событие',
  'LBL_LOCATION' => 'Место',
  'LBL_START_DATE' => 'дата начала',
  'LBL_END_DATE' => 'Дата и время окончания',
  'LBL_BUDGET' => 'Бюджет',
  'LBL_FP_EVENTS_FP_EXPENSES_1_FROM_FP_EXPENSES_TITLE' => 'Расходы', ///
  'LBL_DATE' => 'Начало',
  'LBL_DATE_END' => 'Окончание',
  'LBL_DURATION' => 'Продолжительность',
  'LBL_INVITE_TEMPLATES' => 'Шаблон приглашения',
  'LBL_INVITE_PDF' => 'Отправить приглашения',
  'LBL_EDITVIEW_PANEL1' => 'Детали события', 
  'LBL_DEFAULT_SUBPANEL_TITLE' => 'Участники',
  'LBL_ACCEPT_REDIRECT' => 'Показать страницу при принятии приглашения',
  'LBL_DECLINE_REDIRECT' => 'Показать страницу при отказе от приглашения',
  'LBL_SELECT_DELEGATES' => 'Выбрать участников',
  'LBL_SELECT_DELEGATES_TITLE' => 'Выбор участников:',
  'LBL_SELECT_DELEGATES_TARGET_LIST' => 'Список адресатов',
  'LBL_SELECT_DELEGATES_TARGETS' => 'Адресаты',
  'LBL_SELECT_DELEGATES_CONTACTS' => 'Контакты',
  'LBL_SELECT_DELEGATES_LEADS' => 'Предварит. контакты',
  'LBL_MANAGE_DELEGATES' => 'Указать статус участников',
  'LBL_MANAGE_DELEGATES_TITLE' => 'Указать статус выбранных участников:',
  'LBL_MANAGE_ACCEPTANCES' => 'Результат отправки приглашений',
  'LBL_MANAGE_ACCEPTANCES_TITLE' => 'Указать результат отправки приглашений:',
  'LBL_MANAGE_ACCEPTANCES_ACCEPTED' => 'Принято',
  'LBL_MANAGE_ACCEPTANCES_DECLINED' => 'Отклонено',
  'LBL_MANAGE_POPUP_ERROR' => 'Не выбрано ни одного участника.',
  'LBL_MANAGE_DELEGATES_INVITED' => 'Приглашён',
  'LBL_MANAGE_DELEGATES_NOT_INVITED' => 'Не приглашён',
  'LBL_MANAGE_DELEGATES_ATTENDED' => 'Участвовал',
  'LBL_MANAGE_DELEGATES_NOT_ATTENDED' => 'Не участвовал',
  'LBL_SUCCESS_MSG' => 'Все приглашения успешно отправлены.',
  'LBL_ERROR_MSG_1' => 'Все указанные контакты уже были приглашены.',
  'LBL_ERROR_MSG_2' => 'Отправка приглашений не удалась! Проверьте настройки исходящей почты.',
  'LBL_ERROR_MSG_3' => 'Отправка более чем 10 приглашений не удалась. Убедитесь, что у всех приглашаемых контактов указаны корректные E-mail. (детали содержатся в файле suitecrm.log).',
  'LBL_ERROR_MSG_4' => ' приглашений не удалось отправить. Убедитесь, что у всех приглашаемых контактов указаны корректные E-mail. (детали содержатся в файле suitecrm.log).',
  'LBL_ERROR_MSG_5' => 'Неверный шаблон E-mail',
  'LBL_EMAIL_INVITE' => 'Приглашение',
  
'LBL_FP_EVENTS_CONTACTS_FROM_CONTACTS_TITLE' => 'Контакты',  
'LBL_FP_EVENT_LOCATIONS_FP_EVENTS_1_FROM_FP_EVENT_LOCATIONS_TITLE' => 'Место проведения события',
'LBL_FP_EVENTS_LEADS_1_FROM_LEADS_TITLE' => 'Предварит. контакты',
'LBL_FP_EVENTS_PROSPECTS_1_FROM_PROSPECTS_TITLE' => 'Адресаты',
'LBL_FP_EVENTS_FP_EVENT_DELEGATES_1_FROM_FP_EVENT_DELEGATES_TITLE' => 'Участники',
'LBL_HOURS_ABBREV' => 'час.' ,
'LBL_MINSS_ABBREV' => 'мин.' ,

	// Attendance report
	'LBL_ACCEPT_REPORT' => 'Посещаемость', ///
	'LBL_ACCEPT_REPORT_KEY' => '', ///
	'LBL_CONTACT_NAME' => 'Имя',
	'LBL_ACCOUNT_NAME' => 'Контрагент',
	'LBL_SIGNATURE' => 'Подпись',
	// email templates
	'LBL_EMAIL_ACCEPT' => 'Принять',
	'LBL_EMAIL_DECLINE' => 'Отклонить',
	// contacts/leads/targets subpanels
	'LBL_LIST_INVITE_STATUS_EVENT' => 'Приглашённые',
	'LBL_LIST_ACCEPT_STATUS_EVENT' => 'Статус',
	// counts
	'LBL_NB_INVITES' => 'Приглашено:', ///
	'LBL_NB_ACCEPT' => 'Принято приглашений:',
	'LBL_NB_DECLINED' => 'Отклонено приглашений:',
	'LBL_NB_ATTENDED' => 'Участвовали:',

	'LBL_NAME_FIRST' => 'Имя',
	'LBL_NAME_SECOND' => 'Фамилия',
     
	'LBL_ACTIVITY_STATUS' => 'Статус активности',
  );
//LBL_ERROR_MSG_4 Begins with a number(controller.php line 581) for example 10 emails have failed to send. 

?>