<?php

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_MODULE_NAME' => 'SuiteCRM',
'LBL_NEW_FORM_TITLE' => 'Создать контакт' ,
'LBL_FIRST_NAME' => 'Имя:' ,
'LBL_LAST_NAME' => 'Фамилия:' ,
'LBL_LIST_LAST_NAME' => 'Фамилия' ,
'LBL_PHONE' => 'Тел.:' ,
'LBL_EMAIL_ADDRESS' => 'E-mail:' ,
'LBL_MY_PIPELINE_FORM_TITLE' => 'Диаграмма стадий моих продаж',
'LBL_PIPELINE_FORM_TITLE' => 'Диаграмма стадий общих продаж',
'LBL_RGraph_PIPELINE_FORM_TITLE' => 'Диаграмма стадий общих продаж',
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_NEW_LEAD' => 'Создать предв. контакт' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'LNK_NEW_NOTE' => 'Создать заметку или вложение' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_EMAIL' => 'Отправить E-mail в архив' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_NEW_BUG' => 'Новая ошибка' ,
'LBL_SEARCH_RESULTS' => 'Результат поиска',
'LNK_NEW_SEND_EMAIL' => 'Формирование E-mail' ,
'LBL_NO_ACCESS' => 'Доступ к разделу закрыт. Свяжитесь с администратором системы для получения соответствующих прав.',
'LBL_NO_RESULTS_IN_MODULE' => '-- Нет результатов --',
'LBL_NO_RESULTS' => '<h2>Ничего не найдено. Пожалуйста, повторите поиск.</h2><br>',
'LBL_NO_RESULTS_TIPS' => '<h3>Совет:</h3><ul><li>Убедитесь, что вы отметили необходимые модули.</li><li>Укажите более подробные условия поиска.</li><li>Если вы все ещё ничего не нашли - попробуйте воспользоваться расширенным фильтром соответствующего модуля.</li></ul>',

'LBL_ADD_DASHLETS' => 'Добавить дашлеты',
'LBL_WEBSITE_TITLE' => 'Веб-сайт',
'LBL_RSS_TITLE' => 'Ленты новостей',
'LBL_CLOSE_DASHLETS' => 'Закрыть',
'LBL_CLOSE_SITEMAP' => 'Закрыть',
'LBL_OPTIONS' => 'Параметры',
// dashlet search fields
'LBL_TODAY' => 'Сегодня',
'LBL_YESTERDAY' => 'Вчера',
'LBL_TOMORROW' => ' Завтра ',
'LBL_NEXT_WEEK' => 'Следующая неделя',
'LBL_LAST_7_DAYS' => 'Прошедшие 7 дней',
'LBL_NEXT_7_DAYS' => 'Следующие 7 дней',
'LBL_LAST_MONTH' => 'Прошлый месяц',
'LBL_NEXT_MONTH' => 'Следующий месяц',
'LBL_LAST_YEAR' => 'Прошлый год',
'LBL_NEXT_YEAR' => 'Следующий год',
'LBL_LAST_30_DAYS' => 'Прошедшие 30 дней',
'LBL_NEXT_30_DAYS' => 'Следующие 30 дней',
'LBL_THIS_MONTH' => 'Этот месяц',
'LBL_THIS_YEAR' => 'Этот год',

'LBL_MODULES' => 'Модули',
'LBL_CHARTS' => 'Диаграммы',
'LBL_TOOLS' => 'Разное',
'LBL_WEB' => 'Веб',


// Dashlet Categories
'dashlet_categories_dom' => array(
'Module Views' => 'Модули',
'Portal' => 'Портал',
'Charts' => 'Графики',
'Tools' => 'Сервис',
'Miscellaneous' => 'Разное') ,
'LBL_ADDING_DASHLET' => 'Добавление дашлета...',
'LBL_ADDED_DASHLET' => 'Дашлет добавлен',
'LBL_REMOVE_DASHLET_CONFIRM' => 'Вы действительно хотите удалить этот дашлет?',
'LBL_REMOVING_DASHLET' => 'Удаление дашлета...',
'LBL_REMOVED_DASHLET' => 'Дашлет удалён',
'LBL_DASHLET_CONFIGURE_GENERAL' => 'Основные настройки',
'LBL_DASHLET_CONFIGURE_FILTERS' => 'Фильтры',
'LBL_DASHLET_CONFIGURE_MY_ITEMS_ONLY' => 'Мои записи:',
'LBL_DASHLET_CONFIGURE_TITLE' => 'Заголовок:',
'LBL_DASHLET_CONFIGURE_DISPLAY_ROWS' => 'Отображать строк:',

'LBL_DASHLET_DELETE' => 'Удалить дашлет',
'LBL_DASHLET_REFRESH' => 'Обновить дашлет',
'LBL_DASHLET_EDIT' => 'Настроить дашлет',



// Default out-of-box names for tabs
'LBL_HOME_PAGE_1_NAME' => 'SuiteCRM', ///


'LBL_SEARCH' => 'Найти',
'LBL_CLEAR' => 'Очистить',

'LBL_BASIC_CHARTS' => 'Основные диаграммы',


'LBL_DASHLET_SEARCH' => 'Найти дашлет',

//ABOUT page
'LBL_VERSION' => 'Версия',
'LBL_BUILD' => 'Сборка',





'LBL_SOURCE_SUGAR' => 'Sugar - The world\'s most popular sales force automation application created by SugarCRM Inc.',

'LBL_DASHLET_TITLE' => 'Мои сайты',
'LBL_DASHLET_OPT_TITLE' => 'Заголовок:',
'LBL_DASHLET_INCORRECT_URL' => 'Неверный адрес веб-сайта',
'LBL_DASHLET_OPT_URL' => 'Адрес веб-сайта:',
'LBL_DASHLET_OPT_HEIGHT' => 'Высота дашлета (в пикселях):',
'LBL_DASHLET_SUITE_NEWS' => 'SuiteCRM-новости',
'LBL_DASHLET_DISCOVER_SUITE' => 'Discover Suite', ///
	'LBL_BASIC_SEARCH' => 'Фильтр' /*for 508 compliance fix*/,
	'LBL_ADVANCED_SEARCH' => 'Расширенный фильтр' /*for 508 compliance fix*/,
    'LBL_TOUR_HOME' => 'Home Icon',
    'LBL_TOUR_HOME_DESCRIPTION' => 'Quickly get back to your Home Page dashboard in one click.',
    'LBL_TOUR_MODULES' => 'Modules',
    'LBL_TOUR_MODULES_DESCRIPTION' => 'All your important modules are here.',
    'LBL_TOUR_MORE' => 'More Modules',
    'LBL_TOUR_MORE_DESCRIPTION' => 'The rest of your modules are here.',
    'LBL_TOUR_SEARCH' => 'Full Text Search',
    'LBL_TOUR_SEARCH_DESCRIPTION' => 'Search just got a whole lot better.',
    'LBL_TOUR_NOTIFICATIONS' => 'Notifications',
    'LBL_TOUR_NOTIFICATIONS_DESCRIPTION' => 'Suite application notifications would go here.',
    'LBL_TOUR_PROFILE' => 'Profile',
    'LBL_TOUR_PROFILE_DESCRIPTION' => 'Access profile, settings and logout.',
    'LBL_TOUR_QUICKCREATE' => 'Quick Create',
    'LBL_TOUR_QUICKCREATE_DESCRIPTION' => 'Quickly create records without losing your place.',
    'LBL_TOUR_FOOTER' => 'Collapsible Footer',
    'LBL_TOUR_FOOTER_DESCRIPTION' => 'Easily expand and collapse the footer.',
    'LBL_TOUR_CUSTOM' => 'Custom Apps',
    'LBL_TOUR_CUSTOM_DESCRIPTION' => 'Custom integrations would go here.',
    'LBL_TOUR_BRAND' => 'Your Brand',
    'LBL_TOUR_BRAND_DESCRIPTION' => 'Your logo goes here. You can mouse over for more info.',
    'LBL_TOUR_WELCOME' => 'Welcome to SuiteCRM',
    'LBL_TOUR_WATCH' => 'Watch What\'s New in SuiteCRM',
    'LBL_TOUR_FEATURES' => '<ul style=""><li class="icon-ok">New simplifed navigation bar</li><li class="icon-ok">New collapsible footer</li><li class="icon-ok">Improved Search</li><li class="icon-ok">Updated actions menu</li></ul><p>and much more!</p>',
    'LBL_TOUR_VISIT' => 'For more information please visit our application',
    'LBL_TOUR_DONE' => 'You\'re Done!',
    'LBL_TOUR_REFERENCE_1' => 'You can always reference our',
    'LBL_TOUR_REFERENCE_2' => 'through the "Support" link under the profile tab.',
    'LNK_TOUR_DOCUMENTATION' => 'documentation',
	'LBL_TOUR_CALENDAR_URL_1' => 'Do you share your SuiteCRM calendar with 3rd party applications, such as Microsoft Outlook or Exchange? If so, you have a new URL. This new, more secure URL includes a personal key which will prevent unauthorized publishing of your calendar.',
    'LBL_TOUR_CALENDAR_URL_2' => 'Retrieve your new shared calendar URL.', /// <-



//***Suite***

'LBL_CONTRIBUTORS' => 'Участники проекта',
'LBL_ABOUT_SUITE' => 'О проекте SuiteCRM',
'LBL_PARTNERS' => 'Партнёры',
'LBL_FEATURING' => 'AOS, AOW, AOR, AOP, AOE and Reschedule modules by SalesAgility.',
'LBL_EDIT_ALL_RECURRENCES' => 'Править, включая повторы',
'LBL_REMOVE_ALL_RECURRENCES' => 'Удалить, включая повторы',
'LBL_CONFIRM_REMOVE' => 'Вы действительно хотите удалить эту запись?',

'LBL_CONTRIBUTOR_SUITECRM' => 'Бесплатная альтернатива SugarCRM Professional Edition с открытым исходным кодом    <br>
        <hr><h2>
        <a href="https://community.suitecrm.com/t/suitecrm/54668" target="_blank">Русифицированное Руководство пользователя и администратора SuiteCRM</a></h2>',
'LBL_CONTRIBUTOR_SECURITY_SUITE' => 'SecuritySuite by Jason Eggers',
'LBL_CONTRIBUTOR_JJW_GMAPS' => 'JJWDesign Google Maps by Jeffrey J. Walters',
'LBL_CONTRIBUTOR_CONSCIOUS' => 'SuiteCRM LOGO Provided by Conscious Solutions',
'LBL_CONTRIBUTOR_RESPONSETAP' => 'Contribution to SuiteCRM 7.3 release by ResponseTap',
'LBL_CONTRIBUTOR_GMBH' => 'Workflow Calculated Fields contributed by diligent technology & business consulting GmbH',

'LBL_LANGUAGE_ABOUT' => 'О русификации проекта',
'LBL_LANGUAGE_COMMUNITY_ABOUT' => 'Актуальная версия русификации в виде языкового пакета RAPIRA доступна на сайте GitHub (<a href="https://github.com/likhobory/SuiteCRM-CoreRU" target="_blank">https://github.com/likhobory/SuiteCRM-CoreRU</a>)',
'LBL_LANGUAGE_COMMUNITY_PACKS' => '<a href="https://sourceforge.net/projects/suitecrmtranslations/files" target="_blank">Альтернативный перевод на русский язык</a>, осуществляющийся всеми желающими на основе языковых файлов RAPIRA, доступен на сайте Crowdin',

'LBL_ABOUT_SUITE_2' => 'SuiteCRM распространяется под лицензией GPL3',
'LBL_ABOUT_SUITE_4' => 'Весь исходный код проекта SuiteCRM является открытым и публикуется под лицензией GPL3',
'LBL_ABOUT_SUITE_5' => 'Поддержка SuiteCRM осуществляется как на бесплатной, так и на платной основе',

'LBL_SUITE_PARTNERS' => 'С полным списком наших партнёров, активно поддерживающих проекты с открытым исходным кодом, вы можете ознакомиться на нашем сайте',

'LBL_SAVE_BUTTON' => 'Сохранить',
'LBL_DELETE_BUTTON' => 'Удалить',
'LBL_APPLY_BUTTON' => 'Применить',
'LBL_SEND_INVITES' => 'Сохранить и отправить приглашения',
'LBL_CANCEL_BUTTON' => 'Отказаться',
'LBL_CLOSE_BUTTON' => 'Закрыть',

'LBL_CREATE_NEW_RECORD' => 'Назначить мероприятие',
'LBL_CREATE_CALL' => 'Назначить звонок',
'LBL_CREATE_MEETING' => 'Назначить встречу',

'LBL_GENERAL_TAB' => 'Основное',
'LBL_PARTICIPANTS_TAB' => 'Участники',
'LBL_REPEAT_TAB' => 'Повторы',
	
'LBL_REPEAT_TYPE' => 'Повторять',
'LBL_REPEAT_INTERVAL' => 'Каждые',
'LBL_REPEAT_END' => 'Прекратить',
'LBL_REPEAT_END_AFTER' => 'после',
'LBL_REPEAT_OCCURRENCES' => 'повторов',
'LBL_REPEAT_END_BY' => '',
'LBL_REPEAT_DOW' => 'Дни повторов',
'LBL_REPEAT_UNTIL' => 'Повторять до',
'LBL_REPEAT_COUNT' => 'Число повторов',
'LBL_REPEAT_LIMIT_ERROR' => 'Вы пытаетесь создать более $limit встреч.',

//Events
'LNK_EVENT' => 'Событие',
'LNK_EVENT_VIEW' => 'Просмотр события',
'LBL_DATE' => 'Начальные дата и время: ',
'LBL_DURATION' => 'Продолжительность: ',
'LBL_NAME' => 'Название: ',
'LBL_HOUR_ABBREV' => 'час.',
'LBL_HOURS_ABBREV' => 'час.',
'LBL_MINSS_ABBREV' => 'мин.',
'LBL_LOCATION' => 'Место: ',
'LBL_STATUS' => 'Статус: ',
'LBL_DESCRIPTION' => 'Описание: ',
//End Events

'LBL_ELASTIC_SEARCH_EXCEPTION_SEARCH_INVALID_REQUEST' => 'В процессе поиска произошла ошибка. Проверьте синтаксис поискового запроса.',
'LBL_ELASTIC_SEARCH_EXCEPTION_SEARCH_ENGINE_NOT_FOUND' => 'Поисковый движок не обнаружен. Попробуйте выполнить поиск ещё раз.',
'LBL_ELASTIC_SEARCH_EXCEPTION_NO_NODES_AVAILABLE' => 'Невозможно подключиться к серверу Elasticsearch.',
'LBL_ELASTIC_SEARCH_EXCEPTION_SEARCH' => 'В процессе поиска произошла ошибка.',
'LBL_ELASTIC_SEARCH_EXCEPTION_DEFAULT' => 'В процессе поиска произошла неизвестная ошибка.',
'LBL_ELASTIC_SEARCH_EXCEPTION_END_MESSAGE' => 'Обратитесь к системному администратору, если не удалось решить проблему. Детальная информация сохранена в логах.',
'LBL_ELASTIC_SEARCH_EXCEPTION_MISSING_INDEX' => 'Не удалось найти поисковый индекс для одного или нескольких модулей. Убедитесь, что crontab настроен и запущен, в панели администратора откройте настройки Elasticsearch, запланируйте полную индексацию, а также создайте задание планировщика «Выполнять Elasticsearch-индексацию», если оно не существует.',

'LBL_ELASTIC_SEARCH_DEFAULT' => 'Ничего не найдено. Попробуйте расширить критерии поиска.',

// Portal Labels
'LBL_AOP_DISABLED' => 'Настройки портала отключены, включите их в панели администратора',
'LBL_CREATE_PORTAL_USER_FAILED' => 'Ошибка создания пользователя портала.',
'LBL_ENABLE_PORTAL_USER_FAILED' => 'Ошибка включения пользователя портала.',
'LBL_DISABLE_PORTAL_USER_FAILED' => 'Ошибка отключения пользователя портала.',
'LBL_CREATE_PORTAL_USER_SUCCESS' => 'Пользователь портала успешно создан',
'LBL_ENABLE_PORTAL_USER_SUCCESS' => 'Пользователь портала включён',
'LBL_DISABLE_PORTAL_USER_SUCCESS' => 'Пользователь портала отключён',

'LNK_TASK_VIEW' => 'Просмотр задачи',

);
