<?php
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array (
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
'LBL_ASSIGNED_TO_NAME' => 'Пользователь SuiteCRM',
'LBL_ID' => 'ID',
'LBL_DATE_ENTERED' => 'Дата создания',
'LBL_DATE_MODIFIED' => 'Дата изменения',
'LBL_MODIFIED' => 'Изменено',
'LBL_MODIFIED_ID' => 'Изменено(ID)',
'LBL_MODIFIED_NAME' => 'Изменено',
'LBL_CREATED' => 'Создано',
'LBL_CREATED_ID' => 'Создано(ID)',
'LBL_DESCRIPTION' => 'Описание',
'LBL_DELETED' => 'Удалено',
'LBL_NAME' => 'Имя пользователя приложения',
'LBL_CREATED_USER' => 'Создано',
'LBL_MODIFIED_USER' => 'Изменено',
'LBL_LIST_NAME' => 'Имя',
'LBL_TEAM' => 'Teams', ///
'LBL_TEAMS' => 'Teams', ///
'LBL_TEAM_ID' => 'Team Id', ///
'LBL_LIST_FORM_TITLE' => 'Перечень внешних учётных записей',
'LBL_MODULE_NAME' => 'Внешняя учётная запись',
'LBL_MODULE_TITLE' => 'Внешние учётные записи',
'LBL_HOMEPAGE_TITLE' => 'Мои внешние учётные записи',
'LNK_NEW_RECORD' => 'Создать внешнюю учётную запись',
'LNK_LIST' => 'Внешние учётные записи',
'LNK_IMPORT_SUGAR_EAPM' => 'Импорт внешних учётных записей',
'LBL_SEARCH_FORM_TITLE' => 'Поиск внешнего источника',
'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
'LBL_SUGAR_EAPM_SUBPANEL_TITLE' => 'Внешние учётные записи',
'LBL_NEW_FORM_TITLE' => 'Новая учётная запись',
'LBL_PASSWORD' => 'Пароль',
'LBL_USER_NAME' => 'Имя пользователя приложения',
'LBL_URL' => 'URL',
'LBL_APPLICATION' => 'Приложение',
'LBL_API_DATA' => 'API-данные',
'LBL_API_TYPE' => 'Login Type',
'LBL_API_CONSKEY' => 'Публичный ключ',
'LBL_API_CONSSECRET' => 'Секретный ключ',
'LBL_API_OAUTHTOKEN' => 'OAuth-токен',
'LBL_AUTH_UNSUPPORTED' => 'Данный метод авторизации не поддерживается приложением',
'LBL_AUTH_ERROR' => 'Попытка авторизации внешней учётной записи не удалась.',
'LBL_VALIDATED' => 'Соединение установлено',
'LBL_ACTIVE' => 'Активно',
'LBL_OAUTH_NAME' => '%s',
'LBL_SUGAR_USER_NAME' => 'Пользователь',
'LBL_DISPLAY_PROPERTIES' => 'Параметры',
'LBL_CONNECT_BUTTON_TITLE' => 'Подключить',
'LBL_NOTE' => 'Please Note', ///
'LBL_CONNECTED' => 'Подключено',
'LBL_DISCONNECTED' => 'Не подключено',

'LBL_ERR_NO_AUTHINFO' => 'По данной учётной записи нет регистрационных данных.',
'LBL_ERR_NO_TOKEN' => 'There are no valid login tokens for this account.',

'LBL_ERR_FAILED_QUICKCHECK' => 'Нет соединения с {0}. Нажмите на кнопку "ОК" для восстановления соединения.',

'LBL_CLICK_TO_EDIT' => 'Изменить',

// Various strings used throughout the external account modules
'LBL_MEET_NOW_BUTTON' => 'Назначить встречу на текущее время',
'LBL_VIEW_LOTUS_LIVE_MEETINGS' => 'Просмотр предстоящих встреч LotusLive&trade;',
'LBL_TITLE_LOTUS_LIVE_MEETINGS' => 'Предстоящие встречи LotusLive&trade;',
'LBL_VIEW_LOTUS_LIVE_DOCUMENTS' => 'Просмотр файлов LotusLive&trade;',
'LBL_TITLE_LOTUS_LIVE_DOCUMENTS' => 'Файлы LotusLive&trade;',
'LBL_REAUTHENTICATE_LABEL' => 'Переподключиться',
'LBL_REAUTHENTICATE_KEY' => 'a',
'LBL_APPLICATION_FOUND_NOTICE' => 'Учётная запись для данного приложения уже существует. Мы восстановили существующую учётную запись.',
'LBL_OMIT_URL' => '(Без http:// или https://)',
'LBL_OAUTH_SAVE_NOTICE' => 'Нажмите на кнопку <b>Подключить</b> для перенаправления на страницу ввода регистрационной информации. После успешного подключения вы автоматически вернётесь в SuiteCRM.',
'LBL_BASIC_SAVE_NOTICE' => 'Нажмите на кнопку <b>Подключить</b> для подключения данной учётной записи к SuiteCRM.',
'LBL_ERR_FACEBOOK' => 'Facebook returned an error, and the feed cannot be displayed.', ///
'LBL_ERR_OAUTH_FACEBOOK_1' => 'Facebook authentication was not successful. To attempt authentication, please', ///
'LBL_ERR_OAUTH_FACEBOOK_2' => 'login to Facebook again', ///
'LBL_ERR_NO_RESPONSE' => 'При попытке подключения произошла ошибка.',
'LBL_ERR_TWITTER' => 'Twitter returned an error, and the feed cannot be displayed.', ///
'LBL_ERR_POPUPS_DISABLED' => 'Для успешного подключения разрешите всплывающие окна в вашем браузере или добавьте сайт "{0}" в список исключений.'
);
