<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--

$mod_strings = array (
    'LBL_OAUTH_REQUEST' => 'Токен запроса',
    'LBL_OAUTH_AUTHORIZE' => 'Авторизовать токен',
	'LBL_OAUTH_CONSUMERREQ' => 'Авторизовать токен пользователя <b>%s</b>?',
    'LBL_OAUTH_ROLE' => 'Роль токена',
	'LBL_OAUTH_VALIDATION' => 'Контрольный код',
  	'LBL_ASSIGNED_TO_NAME' => 'Пользователь',
  	'LBL_ID' => 'ID',
    'LBL_STATUS' => 'Статус',
    'LBL_TS' => 'Отметка времени',
    'LBL_LIST_DELETE' => 'Удалён',
    'LBL_CONSUMER' => 'Пользователь',
    'LBL_OAUTH_DISABLED' => 'Поддержка OAuth отключена. Вероятно, отсутствует соответствующее расширение PHP. Для решения вопроса свяжитесь с системным администратором.',
);
