<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************

* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.

 // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  *********************************************************************************/
 // Replaced by RAPIRA <--
 
$mod_strings = array(
'LBL_MODULE_NAME' => 'Мероприятия' ,
'LBL_MODULE_TITLE' => 'Мероприятия - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск мероприятий' ,
'LBL_LIST_FORM_TITLE' => 'Мероприятия' ,
'LBL_LIST_SUBJECT' => 'Тема' ,
'LBL_OVERVIEW' => 'ВСЕ ЗАПИСИ',
'LBL_TASKS' => 'ЗАДАЧИ',
'LBL_MEETINGS' => 'ВСТРЕЧИ',
'LBL_CALLS' => 'ЗВОНКИ',
'LBL_EMAILS' => 'E-MAIL',
'LBL_NOTES' => 'ЗАМЕТКИ',
'LBL_PRINT' => 'Печать',
'LBL_MEETING_TYPE' => 'Встреча',
'LBL_CALL_TYPE' => 'Звонок',
'LBL_EMAIL_TYPE' => 'E-mail',
'LBL_NOTE_TYPE' => 'Заметка',
'LBL_DATA_TYPE_START' => 'Начало:',
'LBL_DATA_TYPE_SENT' => 'Отправлено:',
'LBL_DATA_TYPE_MODIFIED' => 'Изменено:',
'LBL_LIST_CONTACT' => 'Контакт' ,
'LBL_LIST_RELATED_TO' => 'Относится к' ,
'LBL_LIST_DATE' => 'Дата' ,
'LBL_LIST_CLOSE' => 'Закрыть' ,
'LBL_SUBJECT' => 'Тема:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_LOCATION' => 'Место:' ,
'LBL_DATE_TIME' => 'Дата и время начала:' ,
'LBL_DATE' => 'Дата начала:' ,
'LBL_TIME' => 'Время начала:' ,
'LBL_DURATION' => 'Продолжительность:' ,
'LBL_HOURS_MINS' => '(часов:минут)' ,
'LBL_CONTACT_NAME' => 'Контактное лицо: ' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_NEW_NOTE' => 'Создать заметку или вложение' ,
'LNK_NEW_EMAIL' => 'Создать архивный E-mail' ,
'LNK_CALL_LIST' => 'Звонки' ,
'LNK_MEETING_LIST' => 'Встречи' ,
'LNK_TASK_LIST' => 'Задачи' ,
'LNK_NOTE_LIST' => 'Заметки' ,
'LBL_DELETE_ACTIVITY' => 'Вы действительно хотите удалить данное мероприятие?',
'ERR_DELETE_RECORD' => 'Вы должны указать номер записи перед удалением.' ,
'LBL_INVITEE' => 'Приглашённые' ,
'LBL_LIST_DIRECTION' => 'Направление' ,
'LBL_DIRECTION' => 'Направление' ,
'LNK_NEW_APPOINTMENT' => 'Новое назначение' ,
'LNK_VIEW_CALENDAR' => 'Календарь' ,
'LBL_OPEN_ACTIVITIES' => 'Открытые мероприятия' ,
'LBL_HISTORY' => 'История' ,
'LBL_NEW_TASK_BUTTON_TITLE' => 'Создать задачу' ,
'LBL_NEW_TASK_BUTTON_LABEL' => 'Создать задачу' ,
'LBL_SCHEDULE_MEETING_BUTTON_TITLE' => 'Планирование встречи' ,
'LBL_SCHEDULE_MEETING_BUTTON_LABEL' => 'Назначить встречу' ,
'LBL_SCHEDULE_CALL_BUTTON_LABEL' => 'Назначить звонок' ,
'LBL_NEW_NOTE_BUTTON_TITLE' => 'Создать заметку или вложение' ,
'LBL_NEW_NOTE_BUTTON_LABEL' => 'Создать заметку или вложение' ,
'LBL_TRACK_EMAIL_BUTTON_TITLE' => 'Отправить E-mail в архив' ,
'LBL_TRACK_EMAIL_BUTTON_LABEL' => 'Отправить E-mail в архив' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LIST_DUE_DATE' => 'Дата завершения' ,
'LBL_LIST_LAST_MODIFIED' => 'Последнее изменение' ,
'LNK_IMPORT_CALLS' => 'Импорт звонков',
'LNK_IMPORT_MEETINGS' => 'Импорт встреч',
'LNK_IMPORT_TASKS' => 'Импорт задач',
'LNK_IMPORT_NOTES' => 'Импорт заметок' ,
'LBL_ACCEPT_THIS' => 'Принять?' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Открытые мероприятия' ,
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ACCEPT' => 'Принять' /*for 508 compliance fix*/,
);
